### ISSUE TITLE
Optimize source code

### ISSUE THREAD

**Issue by thaihaquang** [rafaelpadilla/Object-Detection-Metrics#10]
Thank you for sharing your work, it saves a lot of my time ^^
However, I have a suggestion to improve the calculating performance. In Evaluator.py, you call GetPascalVOCMetrics() every time you need to calculate mAP of a new class. This process is time-consuming. The return results are the same for every class. 
So, you should calculate the self.results = self.GetPascalVOCMetrics(boundingboxes, IOUThreshold) once at the __init__() class. In the def PlotPrecisionRecallCurve(),  you can use for res in self.results:....
It can save a lot of calculating time.

**Comment by rafaelpadilla** [comment]
Dear @thaihaquang,
Thank you for your suggestion. Next update I will consider your tip.
