### ISSUE TITLE
Question about working with Yolo coordinates

### ISSUE THREAD

**Issue by kostas1515** [rafaelpadilla/Object-Detection-Metrics#100]
Hello and thank you for this brilliant library.
You say in your description that the code can work with yolo coordinates is that correct? Because you support xywh format, which is not the same as x_center, y_center, w, h (which is the yolo format). So should I transform my inputs to xmin, ymin, w, h before using the evaluator, or it works for x_center, y_center as well?
I was also wondering if you pass center coordinates and the algorithm thinks they are the xmin,ymin it will be like translating both the gt and detection to w/2 and h/2, so would the IoU  still work even though boxes may fall outside the image?

**Comment by rafaelpadilla** [comment]
Hi @kostas1515,

Yes, this library accepts different types of coordinates, including YOLO's format.

You don't have to transform your coordinates. You only need to use the correct parameters while creating the `BoundingBox` objects. Please check [this](https://github.com/rafaelpadilla/Object-Detection-Metrics/tree/master/samples/sample_1) sample code.

YOLO's coordinates are relative to the image size. The size of the image is passed to the BoundingBox object with the parameter `imgSize`. For YOLO's coordinates, you also have to use `typeCoordinates=CoordinatesType.Relative`.

I hope it helps.
