### ISSUE TITLE
Formula for interpolating through points

### ISSUE THREAD

**Issue by waldemarmeier** [rafaelpadilla/Object-Detection-Metrics#101]
I think there is a mistake in the formula for interpolating through points:

I think you meant iterating from n=0 to n=N and not from r=0 to r=1.

https://camo.githubusercontent.com/1aca913fb55dbfe3f9f5ed3907019774cb00ddf2/687474703a2f2f6c617465782e636f6465636f67732e636f6d2f6769662e6c617465783f25354373756d5f2537427225334430253744253545253742312537442532302535436c656674253230253238253230725f2537426e2b312537442532302d253230725f6e253543726967687425323025323925323025354372686f5f253742696e746572702537442535436c656674253230253238253230725f2537426e2b312537442532302535437269676874253230253239

**Comment by rafaelpadilla** [comment]
Dear @waldemarmeier,

I reviewed the equation and corrected it. Thank you for your feedback.
