### ISSUE TITLE
How to calculate mean Average Recall (mAR)?

### ISSUE THREAD

**Issue by WillianaLeite** [rafaelpadilla/Object-Detection-Metrics#102]
I customized the "https://github.com/matterport/Mask_RCNN.git" repository to train with my own data set, for object detection, ignoring the segmentation part of the mask. Now, I am evaluating my results, I can calculate the MAP through the function: compute_ap, in "https://github.com/matterport/Mask_RCNN/blob/master/mrcnn/utils.py" which is similar to the one you present in Evaluate.py with the function "CalculateAveragePrecision". I would like to know if you know the correct way to calculate the average recall average (mAR) using the standard for all VOC2010 interpolations?

**Comment by rafaelpadilla** [comment]
Hi @WillianaLeite,

The Average Recall (AR) is not used in the VOC challenge, thats why I did not include it in code. But someday I would like to add the AR metric in the project. 

I do not have many details of the AR implementation. This metric is covered in the [COCO dataset](http://cocodataset.org/#detection-eval) and recommend you to take a look at [the official coco code](https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/cocoeval.py).

Sorry for not being able to provide you more details on that.
