### ISSUE TITLE
Precision Recall Curve

### ISSUE THREAD

**Issue by nisarggandhewar** [rafaelpadilla/Object-Detection-Metrics#103]
Do we need to draw precision recall curve for YOLO object detector manually or is their any command to generate it.

**Comment by rafaelpadilla** [comment]
Dear @nisarggandhewar,

The precision x recall curve is plotted automatically when you run the script. (ex: `python pascalvoc.py -t 0.3`). 

For YOLO, you just have to inform the specific tags to consider the relative format of the bounding boxes. See the instructions [here](https://github.com/rafaelpadilla/Object-Detection-Metrics#how-to-use-this-project).

Best regards

**Comment by BoHuang-ecr** [comment]
Hello,
For my prediction, there is no confidence score there. 
So the precision-recall curve is plotted based on difference IOU threshold (determine TP or FP)?
