### ISSUE TITLE
Can a ground truth text file be empty

### ISSUE THREAD

**Issue by skye95git** [rafaelpadilla/Object-Detection-Metrics#105]
There is no target object in a picture，so there is no ground truth. Does an empty ground truth text file affect AP calculations? Adding an empty ground truth text file and not adding an empty ground truth text file can make a big difference in calculating an AP. Which result should I go with?

**Comment by rafaelpadilla** [comment]
@skye95git ,

You have a good point. All ground truth images must have an associated .txt file. If you do not provide a file, it is like your ground truth image does not exist and will not be taken into account.

On the other hand, if an empty ground truth is added, your detection system may detect objects on this ground truth (FP).

In my opinion the correct and fair is to consider the empty ground truth images to test the robustness of your object detector system.
