### ISSUE TITLE
map without confidence score for single class detection

### ISSUE THREAD

**Issue by frozenking4444** [rafaelpadilla/Object-Detection-Metrics#106]
I am creating Bounding Boxes for a single type of object from the binary segmentation mask provided by a Unet. So, I have ground truth and predicted Bounding Boxes but no confidence score. Should I use 1 as confidence for each of them?

**Comment by rafaelpadilla** [comment]
@frozenking4444 

For your ground truth you do not specify any confidence (see instructions [here](https://github.com/rafaelpadilla/Object-Detection-Metrics/blob/master/README.md#create-the-ground-truth-files)).

I am not much familiar with Unet outputs. Doesn't it provide confidence score for its detection? How do the works make evaluations with this network?

**Comment by frozenking4444** [comment]
Thanks for your reply. I know there is no confidence for ground truth. The general question is : "what do you do if your detection model only provides Bounding Box without confidence value or class probability (single class detection)". Unet is a semantic segmentation algorithm which provides pixel wise classification. So, they normally use average iou as a metric. I hope it's clear. Waiting for your reply and again thank you very much again for replying to my question.

**Comment by rafaelpadilla** [comment]
@frozenking4444 ,

If your model does not provide confidences, I believe considering all detections with the same confidence would be a reasonable solution. Am I right?

For pixel-wise classifications other metrics could be used, such as the PSQ as described in [this](https://www.youtube.com/watch?v=pDhCbYc0NBQ&t=4363s) video.

**Comment by rafaelpadilla** [comment]
As the question in this issue was answered and has not received any comments, this issue will be closed.
