### ISSUE TITLE
what is confidences ?

### ISSUE THREAD

**Issue by Ersin26** [rafaelpadilla/Object-Detection-Metrics#109]
I want to draw my object detection project's precision - recall graph. But i don't have confidences value. How can i calculate confidances for my object detection results.

**Comment by rafaelpadilla** [comment]
Hi @Ersin26,

Usually object detection frameworks output the confidence levels for each detected bounding box. 

I do not have much details about the problem you are trying to solve, but if your bounding boxes have the same confidences, you could set them all to 1.

**Comment by rafaelpadilla** [comment]
As the question in this issue was answered and has not received any comment, this issue will be closed.
