### ISSUE TITLE
[request] Simpler API

### ISSUE THREAD

**Issue by mattans** [rafaelpadilla/Object-Detection-Metrics#113]
Hi, great work.
I have an issue regarding https://github.com/rafaelpadilla/Object-Detection-Metrics/blob/master/pascalvoc.py

Is it possible to extract the metric function to a separate class? and then maybe let pascalvoc.py import it and call it.
What I mean is that it would be great to have an implementation of a simple function,

`get_pascal_score(list_of_gt_bboxes, list_of_pred_bboxes, list_of_pred_confidences)
`
Which returns a scalar result, without the overhead of the non-logic-related code.
I tried to extract such a function from pascalvoc.py but the metric and the program are too entangled with each other for me.

Thanks

**Comment by LHFO94** [comment]
+1

**Comment by rafaelpadilla** [comment]
Hi @mattans ,

Thanks for your feedback. But the code is far from non-logic. Python is an object-oriented language, and the code was done using OO components, so people could benefit from the small components for other purposes.

Anyway, I understand your need. But according to your suggestion, how would you pass the information of which images each bounding box belongs to?

In your suggestion, I believe you would have to call the `get_pascal_score` function for each image. Which would make no sense to return a value for a single image. Let me know what you have in mind.

Best regards

**Comment by rafaelpadilla** [comment]
As this issue has been answered and no comment has been received ever since, this issue will be closed.
