### ISSUE TITLE
how to create detection file and result file?

### ISSUE THREAD

**Issue by JerrySor** [rafaelpadilla/Object-Detection-Metrics#115]
I do not understand how to create detection and result file, could you help me please?

**Comment by sxngho** [comment]
I created it by writing a file from the test.py I'm using.
```
f = open("imageFileName.txt", 'w')
f.writelines(*** your var(label, x1, y1, x2, y2)***
f.close()
```

**Comment by renhongtao** [comment]
this is must by your self. such as you have five pictures detect. 
01.jpg  02.jpg 03.jpg 04.jpg 05.jpg
then you should have  5  ground trueth file. 
01.txt  02.txt 03.txt   04.txt 05.txt
the  contents in 01.txt  such as :
 person 25 16 38 56

then  the detection result file .you ask .should  in another floder.  must the same name of jpg. and is the same as ground truth. such as
01.txt   02.txt  03.txt 04.txt 05.txt
the  contents in 01.txt  such as:
person .88 5 67 31 48

you can create  the files by  computer  or  by  hand.

**Comment by JerrySor** [comment]
Thank

**Comment by JerrySor** [comment]
Thank

**Comment by JerrySor** [comment]
Thank for your advice

**Comment by JerrySor** [comment]
Thank for your advice

**Comment by JerrySor** [comment]
Thank for your advice

**Comment by JerrySor** [comment]
Thank for your advice

**Comment by JerrySor** [comment]
Thank for your advice

**Comment by JerrySor** [comment]
Thank for your advice

**Comment by JerrySor** [comment]
Thank for your advice

**Comment by JerrySor** [comment]
Thank for your advice

**Comment by JerrySor** [comment]
Thank for your advice

**Comment by JerrySor** [comment]
Thank for your advice!

**Comment by JerrySor** [comment]
Thank for your advice!

**Comment by JerrySor** [comment]
Thank for your advice!

**Comment by JerrySor** [comment]
Thank for your advice!

**Comment by JerrySor** [comment]
Thank for your advice!

**Comment by JerrySor** [comment]
Thank for your advice!

**Comment by JerrySor** [comment]
Thank for your advice!

**Comment by JerrySor** [comment]
Thank for your advice!

**Comment by JerrySor** [comment]
Thank for your advice!

**Comment by JerrySor** [comment]
Thank for your advice!

**Comment by JerrySor** [comment]
Thank for your advice!

**Comment by JerrySor** [comment]
Thank for your advice!

**Comment by JerrySor** [comment]
Thank for your advice!

**Comment by JerrySor** [comment]
Thank for your advice!

**Comment by JerrySor** [comment]
Thank for your advice!

**Comment by JerrySor** [comment]
Thank for your advice!

**Comment by JerrySor** [comment]
Thank for your advice!

**Comment by JerrySor** [comment]
Thank for your advice!

**Comment by JerrySor** [comment]
Thank for your advice!

**Comment by JerrySor** [comment]
Thank for your advice!

**Comment by JerrySor** [comment]
Thank for your advice!

**Comment by JerrySor** [comment]
Thank for your advice!
