### ISSUE TITLE
Wrong Ap value ?use the default  data in groundtruths  and detections?

### ISSUE THREAD

**Issue by renhongtao** [rafaelpadilla/Object-Detection-Metrics#116]
In  ReadMe file have write out the all calculate  process and result.
as the ground truth box in "groundtruths" floder. 
 cat groundtruths/*.txt    format is <name>  <left> <top> <width> <height>

person 25 16 38 56
person 129 123 41 62
person 123 11 43 55
person 38 132 59 45
person 16 14 35 48
person 123 30 49 44
person 99 139 47 47
person 53 42 40 52
person 154 43 31 34
person 59 31 44 51
person 48 128 34 52
person 36 89 52 76
person 62 58 44 67
person 28 31 55 63
person 58 67 50 58

and the detections in detection floder. are:
person .88 5 67 31 48
person .70 119 111 40 67
person .80 124 9 49 67
person .71 64 111 64 58
person .54 26 140 60 47
person .74 19 18 43 35
person .18 109 15 77 39
person .67 86 63 46 45
person .38 160 62 36 53
person .91 105 131 47 47
person .44 18 148 40 44
person .35 83 28 28 26
person .78 28 68 42 67
person .45 87 89 25 39
person .14 10 155 60 26
person .62 50 38 28 46
person .44 95 11 53 28
person .95 29 131 72 29
person .23 29 163 72 29
person .45 43 48 74 38
person .84 17 155 29 35
person .43 95 110 25 42
person .48 16 20 101 88
person .95 33 116 37 49
but  run as :  python pascalvoc.py -gt=./groundtruths -det=./detections/ -gtformat=xywh -detformat=xywh
AP: 2.22% (person)
mAP: 2.22%
the result is  not as the ReadMe.md file wirte: 26.8 %.  and myself detections  calculate  also  not right. 
Anyone  make sure  run the cmd as I. 
Get  the  right result  26.8%????
![image](https://user-images.githubusercontent.com/3240933/87939964-6af78680-cacb-11ea-8d5f-6c5dd513bc07.png)

**Comment by rafaelpadilla** [comment]
Hi @renhongtao, 

Could you please, share the files you have in the `groundtruths` and `detections` folders, so I can replicate the problem you are facing?

Make sure the file `detections/a.txt `contains the detected bounding boxes that are annotated at the file with the same name at the groundtruths folder (`groundtruths/a.txt`).

**Comment by renhongtao** [comment]
I find  the problem.  Is the thresold not set.  In ReadMe.md  file  the  result 26%  is  use Iou  thresold as 0.3.
the  command I have run  not set ,so the code run as the default  is 0.5.
If  use the default the value as 0.3.
![image](https://user-images.githubusercontent.com/3240933/88023724-1fdd8200-cb64-11ea-959d-94106b73f775.png)

python pascalvoc.py -gt=./groundtruths -det=./detections/ -gtformat=xywh -detformat=xywh -t=0.3
AP: 24.57% (person)
mAP: 24.57%

![image](https://user-images.githubusercontent.com/3240933/88023678-0d634880-cb64-11ea-978c-a0e22c7296a7.png)

**Comment by rafaelpadilla** [comment]
Nice. 

I'm going to close this issue.
