### ISSUE TITLE
It's not cool to recursively wipe directory, where the plot should be saved

### ISSUE THREAD

**Issue by adopitonak** [rafaelpadilla/Object-Detection-Metrics#117]
From README.md:
-sp,--savepath | folder where the plots are saved

However when you look at the code:
https://github.com/rafaelpadilla/Object-Detection-Metrics/blob/d94130e8925546e2d665548ddf1a15c56b37d645/pascalvoc.py#L296
it wipes the entire savepath.

As I wanted to test this script with default pascalvoc.py, it wiped my entire project, which was luckily backed up. 

However I wonder how many people were affected by this, since I was not far from saving the plot to my home directory or somewhere I can quickly find it to see what it does.

I would definitely either remove the line of code or write a big warning to the parameter in README.md

**Comment by rafaelpadilla** [comment]
Dear @adopitonak,

This issue had been reported before and we agree that it should have warned the user before cleaning the folder beforehand.

I have fixed this problem as seen [here](https://github.com/rafaelpadilla/Object-Detection-Metrics/blob/master/pascalvoc.py#L295). Now the user is asked to confirm the exclusion of the contents of the folder before adding new results.

I think this issue can be closed now.

Thank you for providing your feedback.

Best regards,
Rafael
