### ISSUE TITLE
confusion matrix

### ISSUE THREAD

**Issue by lrscse** [rafaelpadilla/Object-Detection-Metrics#120]
Hi @rafaelpadilla  how to generate confusion matrix  when both ground truth and prediction value are obtain?

**Comment by rafaelpadilla** [comment]
@lrscse ,

That is a good question. I am not sure how you would create the confusion matrix once you dont have the True Negatives.

Have you seen any object detection work using confusion matrices?

**Comment by lrscse** [comment]
@rafaelpadilla  yes in few paper. Moreover will it possible from your repo to generate mAP for 6 classes apart from individual AP. along with True and false positives disgramatically? like in Cartucho/mAP repo?

**Comment by rafaelpadilla** [comment]
@lrscse How do they obtain the True Negatives in order to generate the confusion matrix?

Our repo generates AP individually for each class as seen [here](https://github.com/rafaelpadilla/Object-Detection-Metrics/blob/master/pascalvoc.py#L352) as well as recall and precision.

You could adapt the outputs to generate plots. Feel free to open a PR if that is the case.

**Comment by lrscse** [comment]
@rafaelpadilla  I am just curious if from yout repo can generate more info. about inference like diagram i below as output
![Ground-Truth Info](https://user-images.githubusercontent.com/58855073/96112959-0e0c4080-0f01-11eb-9bf2-b96a664bc2de.png)
![lamr](https://user-images.githubusercontent.com/58855073/96112966-106e9a80-0f01-11eb-88a2-9f8590ea89a1.png)
![Predicted Objects Info](https://user-images.githubusercontent.com/58855073/96112971-11073100-0f01-11eb-82a4-f4a10f4a1309.png)

**Comment by rafaelpadilla** [comment]
@lrscse ,

Yes, it can be implemented. All the information needed to generate this plots is available in the code.

Could you help us to implement this feature?

**Comment by lrscse** [comment]
i would like to generate such plots using your repo..

**Comment by rafaelpadilla** [comment]
I understand that. But this feature has to be implemented.

In a short time, it will not have it. Unless someone implements it.
