### ISSUE TITLE
[Question] Is COCO implemented?

### ISSUE THREAD

**Issue by austinmw** [rafaelpadilla/Object-Detection-Metrics#122]
README mentions easy of use of metrics for different competitions and mentions COCO, but I don't see utilities for it. Is there some other way to set .5:.95 IoU?

**Comment by rafaelpadilla** [comment]
Hi @austinmw ,

It is not implemented yet. It can be adapted though: You would need to create a routine to go over the 10 IOU values (from .5 to .95 with steps of 0.05) and average the obtained results.

It is not a big deal, but I agree it would be useful to make it available within this repository.
