### ISSUE TITLE
How can we get false negative?

### ISSUE THREAD

**Issue by masouduut94** [rafaelpadilla/Object-Detection-Metrics#123]
In [here](https://github.com/rafaelpadilla/Object-Detection-Metrics/blob/0e32f412af30004741d99bae17227d1a531cd286/lib/Evaluator.py#L50) you just commented that it is a false negative, however I think it is False positive according to calculations.

How can I return the false negatives?

**Comment by rafaelpadilla** [comment]
Hi @masouduut94,

Thanks for pointing the mistake on the comment. I have just fixed that.

Answering your question.
As a False Negative (FN) is a not detected ground truth, you could obtain it by:

FN = total number of ground truth positives - TP

In the function you mentioned (`get_pascal_voc_metrics`), you would have to add the FN in the returning dictionary:

```
r = {
                'class': c,
                'precision': prec,
                'recall': rec,
                'AP': result['ap'],
                'interpolated precision': result['mpre'],
                'interpolated recall': result['mrec'],
                'total positives': npos,
                'total TP': np.sum(TP),
                'total FP': np.sum(FP),
                'total FN': npos-np.sum(TP)
            }

```

I hope it helps

**Comment by masouduut94** [comment]
Great!
Thank you
