### ISSUE TITLE
Missing confidence score in README for detection output 

### ISSUE THREAD

**Issue by cannguyen275** [rafaelpadilla/Object-Detection-Metrics#124]
Dear,
Pls help to check this step in README file, why detection format xywh doesn't require confidence score but xyrb format does:

https://github.com/rafaelpadilla/Object-Detection-Metrics/blob/master/README.md#create-your-detection-files

Thanks,

**Comment by rafaelpadilla** [comment]
@cannguyen275 ,

Thank you for your comment. You are right. <confidence> was missing in the text.  It has been fixed.

Thank you
