### ISSUE TITLE
image in README is broken

### ISSUE THREAD

**Issue by IvyGongoogle** [rafaelpadilla/Object-Detection-Metrics#125]
Hello, many images in README is broken. Can you fix it?

**Comment by rafaelpadilla** [comment]
Hi @IvyGongoogle,

Which images? I have just opened it in Firefox and Chrome and they seem ok.

Could you please point out which images you are not able to see?

**Comment by IvyGongoogle** [comment]
@rafaelpadilla Thanks for your reply.  Look at ![image](https://user-images.githubusercontent.com/13058184/97257274-640dac00-1850-11eb-911b-210feea58251.png)

**Comment by rafaelpadilla** [comment]
@IvyGongoogle,

Good! :)

Thanks.
