### ISSUE TITLE
Can we use confidence score as a parameter when we launch pascalvoc.py

### ISSUE THREAD

**Issue by constantinfite** [rafaelpadilla/Object-Detection-Metrics#126]
Is it possible to fix the confidence score, and we only take the detection box which have a confidence score over or equal to the confidence score we fixed ?

**Comment by rafaelpadilla** [comment]
@constantinfite,

As this is not an option for the PASCAL VOC metric, it is not implemented in our repo. This is something that should be determined by the model (detector) not by the evaluator.

But this suggestion was opened in this [PR](https://github.com/rafaelpadilla/Object-Detection-Metrics/pull/29). I believe this is what you are looking for.

I hope it helps :)
