### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by wohenbushuang** [rafaelpadilla/Object-Detection-Metrics#127]
I believe that 

https://github.com/rafaelpadilla/Object-Detection-Metrics/blob/5219f40c7d15c444f0e72a569d8f0b5cdf311bd0/README.md#L191 

`15 ground truth objects representented by ...` should be `represented`

**Comment by rafaelpadilla** [comment]
@wohenbushuang ,

Thank you for your attentive eyes :)

It has been corrected.
