### ISSUE TITLE
The AP results are different from the official Matlab implementation

### ISSUE THREAD

**Issue by GesilaA** [rafaelpadilla/Object-Detection-Metrics#128]
in this repository, mAP is ~75%
but in Matlab code, mAP is ~81% (2007 format) and ~84% (2012 format)

**Comment by rafaelpadilla** [comment]
@GesilaA ,

Did you use the same threshold? Could you please share the XML files so we can replicate the test?

**Comment by rafaelpadilla** [comment]
Hi @GesilaA,

I would like to know if you repeated your experiments considering the difficult tag being 1.

I repeated all tests and the only difference is this tag.

I will close this issue and feel free to reopen it if you need more help on that.

BR
