### ISSUE TITLE
Issues with Graph and Precision and Recall 

### ISSUE THREAD

**Issue by gcelio** [rafaelpadilla/Object-Detection-Metrics#130]
![image](https://user-images.githubusercontent.com/52965518/102760716-cf449d80-432a-11eb-8e79-d602e7556c25.png)

Hi Rafael,
I would like to confirm that there is nothing wrong with this graph. Precision seems to be going to up to 10 and the number on top (1e-5 + 9.999e-1 = 0.9991 ~ 1.0). So if I were to multiply that to 10 (the precision value at zero), I still get roughly 10.
Shouldn't Precision and Recall always be normalized between 0 and 1 due to the of the way they are defined and calculated?

Also, the result.txt file contains arrays of Recall and Precision. In order to characterize the Precision and Recall of an entire detection model, does this correspond to the last entry of each array. If not how to get infer those values from the arrays.

Thank you very much.

**Comment by rafaelpadilla** [comment]
@gcelio ,

Your results seem strange. Precision and Recall values should be max at 1.

Something is wrong with your files containing the detection and/or ground-truth annotations. Could you please share them, so I take a look at them?

Best regards,
Rafael

**Comment by gcelio** [comment]
Hi Rafael,

I have attached the corresponding result.txt file and it seems like it looks good btw 0 an 1. I have also looked at the detection and ground truth files as well and they all look normal. Yes, this is really strange.

[results.txt](https://github.com/rafaelpadilla/Object-Detection-Metrics/files/5738657/results.txt)

**Comment by rafaelpadilla** [comment]
Hi @gcelio,

I would like to take a look at the detections and ground-truth text files
you used as the input for the object detection evaluator.

You sent me the file with results only.

Em qui., 24 de dez. de 2020 às 06:20, gcelio <notifications@github.com>
escreveu:
