### ISSUE TITLE
How does your code implement PASCAL Voc 2012 AP 

### ISSUE THREAD

**Issue by JamesMcCullochDickens** [rafaelpadilla/Object-Detection-Metrics#132]
Hello, I am curious how your code works for the PASCAL Voc 2012 AP in the case that there is only one distinct recall value,
i.e. the recall precision pairs are something like (0.5, 0.7), (0.5, 0.8) for two different confidence values. I am asking since the formula requires that there be at least two distinct recall values for a class for the end result not to be 0, but it would seem off
to give a value of 0 average precision for the scores listed above.

Also similarly what would occur in the case of only a single recall precision pair? I.e. the case of a single confidence value for a class (unlikely to occur, but I am trying to understand the edge cases). 

Thanks for the great work.

**Comment by rafaelpadilla** [comment]
@JamesMcCullochDickens ,

You have to plot these two points on the Precision x Recall graph and compute the AP based on the all-point interpolation approach. For that you have to calculate the area under the interpolated curve.

I don't understand when you say the formula requires two distinctive recall values. Have you followed the example in the README?

**Comment by JamesMcCullochDickens** [comment]
As in $r_n, r_{n+1}$ requires 2 distinct r values no? I guess you are adding the recall-precision endpoints
(0, 1) and (1,0) to the overall ordered set of points (ordered by recall) and then the formula works for the two edges cases:
- no detections (should give 0)   (1-0)*0 = 0 according to the formula
- one recall precision pair (r_1, p_1), should give (r_1-0)*p_1 + (1-r_1)*( 0) = r_1*p_1

Anyway no big deal. Thanks for the hard work, your examples helped me to understand this problem much better.

**Comment by rafaelpadilla** [comment]
@JamesMcCullochDickens,

Oh yes, I see your doubt now. And you already answered it. :) The endpoints are added so the areas can be measured.

In our recent published work, this extra points are cleared explained in section "4.2.2. All-Point Interpolation". I will leave here the links in case you want to check it.
[[Github](https://github.com/rafaelpadilla/review_object_detection_metrics)] [[paper](https://github.com/rafaelpadilla/review_object_detection_metrics/blob/main/published_paper.pdf)]

Thanks!
