### ISSUE TITLE
Question - Should we send all the detections or filtered detections(based on confidence threshold) to the library for calculation of APs?

### ISSUE THREAD

**Issue by shubh1608** [rafaelpadilla/Object-Detection-Metrics#134]
Hi @rafaelpadilla , 

First of all, Thanks to you for coming up with this useful library. I am working on my research work and using your library for evaluating multiple object detection models.

However I have a question, I noticed that the object detection models return a number of detections with different confidence thresholds let's say in 100. But only a few of them are helpful with high confidence thresholds. 

I evaluated my model by providing a list of detections that are filtered on confidence threshold i.e keep only those detections that have a score > 0.5.

Now, I am not sure what effect it will have on AP or other metrics. Do we need to send an unfiltered detection list? i.e send all the detection boxes for 100 detections and not just the boxes with high confidence scores?

Thanks.

**Comment by rafaelpadilla** [comment]
@shubh1608 

The AP considers **all** confidence levels. It evaluates how well (high recall and high precision) your detector performs with different confidence values. It is all explained in the [paper](https://github.com/rafaelpadilla/Object-Detection-Metrics/raw/master/paper_survey_on_performance_metrics_for_object_detection_algorithms.pdf). Therefore, you should use all 100 detections.

Recently we extended our repository with a new one, implementing more metrics and with a GUI that can saves time during the process. You can check it [here](https://github.com/rafaelpadilla/review_object_detection_metrics) if you want.

**Comment by shubh1608** [comment]
@rafaelpadilla  - Got it! Thanks for the quick response. I will go through the paper once for a better understanding. 
And, yes I was looking for more metrics, I will check your new repo.
Glad you mentioned it here. Keep it up.
