### ISSUE TITLE
Question about box area computation code

### ISSUE THREAD

**Issue by developer0hye** [rafaelpadilla/Object-Detection-Metrics#136]
https://github.com/rafaelpadilla/Object-Detection-Metrics/blob/6a3cee6a2132f03e201867752c721693b563fb03/lib/Evaluator.py#L414

https://github.com/rafaelpadilla/Object-Detection-Metrics/blob/6a3cee6a2132f03e201867752c721693b563fb03/lib/Evaluator.py#L426

Why  do you add 1 to compute box area?

**Comment by rafaelpadilla** [comment]
Hi @developer0hye 

The object is considered to be within the bounding box area, considering the outer border.

So a bounding box with x,y,x2,y2 = 44,55,44,55 is considered to have area = 1 pixel. If we do not add one, it would be 0.

**Comment by developer0hye** [comment]
@rafaelpadilla 
Thanks!
