### ISSUE TITLE
xyrb question

### ISSUE THREAD

**Issue by svideloc** [rafaelpadilla/Object-Detection-Metrics#140]
Hello,

when we specify the gtFormat as "xyrb" -- is this saying that the origin of the picture is the top left portion of the image?

Thanks,
sam

**Comment by rafaelpadilla** [comment]
Hi @svideloc 

Yes, in both cases (xyrb and xywh) the origin is in the top left of the image.

By the way, this repository was updated with a newer version that supports different bounding box formats, so you wouldnt have to worry about transforming existing formats to xyrb or xywh. The link is:

[https://github.com/rafaelpadilla/review_object_detection_metrics](https://github.com/rafaelpadilla/review_object_detection_metrics)
