### ISSUE TITLE
format error

### ISSUE THREAD

**Issue by irum** [rafaelpadilla/Object-Detection-Metrics#147]
Hi,
I have got the following error :  " directory with the ground truth was not specified or do not contain annotation in the chosen format".
I am giving the following format and i have chosen yolo format.

bottles 232 120 307 264
bottles 305 235 342 309
bottles 635 139 692 253
bottles 683 179 738 279
bottles 723 124 783 256
bottles 894 175 959 278
bottles 491 179 534 266
cans 205 262 271 317
cans 306 210 344 267
cans 334 192 374 258
cans 585 318 623 357
cans 610 224 647 287
cans 766 242 828 279
cans 778 204 820 257
cloth 736 311 854 383
cloth 855 306 958 376
gloves 140 136 238 300
gloves 343 297 519 366
gloves 817 135 896 259
metal objects 360 234 383 296
metal objects 356 292 417 317
metal objects 400 236 422 294
metal objects 509 241 550 301
metal objects 407 191 470 257
metal objects 457 252 486 289
pipe joints 526 306 561 352
pipe joints 909 266 948 312
plastic pipes 581 286 717 350
sponges 164 305 268 379
sponges 678 279 746 323
sponges 518 186 606 245
wood 561 241 596 280
wood 782 264 864 308
wood 834 251 890 288

Could you please help me on this.
In terminal i am getting the following message ."empty filename passed to a function" while i am passing the correct directory which contains all  annotations  text files of each image e.g 0.txt for 1st image , 1.txt for 2nd image and so on.

**Comment by rafaelpadilla** [comment]
Hi @irum ,

Could you please attach some of your detection + ground-truth files and images, so I can try to replicate your problem? This current repository requires that all images have the same resolution.

We released a new repository which makes extra verifications in the files. You could try it:
https://github.com/rafaelpadilla/review_object_detection_metrics
Maybe the problem your are facing here does not happen in the new repository.

**Comment by irum** [comment]
Hi @rafaelpadilla ,

Thank you for your reply but i fixed my problem
