### ISSUE TITLE
Is it possible to have a FP and FN at the same time?

### ISSUE THREAD

**Issue by dariogonle** [rafaelpadilla/Object-Detection-Metrics#152]
The green box is the ground truth and the red the predicted box. If I set the iou threshold to 0.5 I would consider this prediction as a bad prediction, so it would be a FP. But as the ground truth is not detected would it count as well as a FN?

I mean does this count as FP, or as a FP and FN?

![image](https://user-images.githubusercontent.com/80393891/121323691-52c16d80-c910-11eb-9d23-44cbd022d003.png)

Thank you.

**Comment by rafaelpadilla** [comment]
@dariogonle 
As your detection (positive) missed the object, it will be counted as FP and, as your groundtruth is not detected by any other positive, it will be counted as FN.

Observations:
Note that to calculate the Precision and Recall, the FN appears in the denominator of the Recall, as Recall = TP/(TP+FN), where TP+FN=all ground truths.  So, in fact, you dont have to compute FN, you just have to consider 'all ground truths'.
