### ISSUE TITLE
get different AP when  equal confidences 

### ISSUE THREAD

**Issue by JianTang2000** [rafaelpadilla/Object-Detection-Metrics#154]
in the README.md ,  "An ilustrated example"

"For this, first we need to order the detections by their confidences, then we calculate the precision and recall for each accumulated detection as shown in the table below "

There seems to be a problem: 

detection R and Y have  equal confidences = 95%,  
if sort R before  Y we get (as ilustrated) : 
detection    conf  TP  FP  pre    rec 
R                95%   1   0    1       0.0666
Y                95%   0   1    0.5     0.0666

**BUT** if sort Y before  R we get : 
detection    conf  TP  FP  pre    rec 
Y                95%   0    1    0       0
R                95%   1    0    0.5     0.0666

these two can lead to **different AP** value by using 11-point interpolation or all points ,

so ... Should I be worried about this ?  (perhaps the case where two confidences are exactly equal will not occur ? )

**Comment by rafaelpadilla** [comment]
@JianTang2000 ,

Yes, you are right. Such cases might happen when confidence levels are exactly the same. 

But in practical cases, confidence levels output by models are represented with many decimal cases, which may not be exactly the same. Also, if your database has a lot of ground-truths and detections, such differences might be completely imperceptible.

In such a specific case, when two of more detections have the same confidence levels, the official PASCAL VOC tool (and also our tool) considers the first reported detections as having the priority.

So, nothing to worry about. :)
