### ISSUE TITLE
Is this a BUG?

### ISSUE THREAD

**Issue by fmo-voxelcloud** [rafaelpadilla/Object-Detection-Metrics#155]
https://github.com/rafaelpadilla/Object-Detection-Metrics/blob/c0fe8a61175e787310aa966d236ebfc0759a5b66/lib/BoundingBox.py#L141

Is this could be: 
`det1ImgSize[0] ==  det2ImgSize[0] and \
 det1ImgSize[1] == det2ImgSize[1]:
`
???

**Comment by rafaelpadilla** [comment]
Hi @fmo-voxelcloud 

This function is never reached by the purpose of this project, so it does not impact the results. But it has been fixed. 

Thank you for noticing that and reporting it :)

Best regards.
