### ISSUE TITLE
How to calculate precision of small, medium and large objects ? 

### ISSUE THREAD

**Issue by RicRicci22** [rafaelpadilla/Object-Detection-Metrics#156]
Hi, 
I am trying to calculate the precision of an algorithm on small medium and large objects. 
For instance I pose constraints on the area, 
area<150 ----- small 
area>500 ----- large 
150<area<500 ----- medium

How can I calculate the precision for these type of objects? Because I am confused by the fact that the predictions can have different size, but referring to the same true objects, depending on how good is the detector. 
In this case, how can I know that a predicted bounding box was meant to detect a small, a medium or a large object?? 
I am so confused by this...

Thank you!

**Comment by tooHotSpot** [comment]
@RicRicci22 Try pycocotools

**Comment by rafaelpadilla** [comment]
@RicRicci22

This repo involves only PASCAL VOC metrics, therefore it does not involve the area of the bounding boxes. COCO metrics takes into consideration the areas.

You could also refer to the new version of our tool and change the sizes criteria. It was explained in details [here](https://github.com/rafaelpadilla/review_object_detection_metrics/issues/70).
