### ISSUE TITLE
missing else part: if not, the box should be a FP.

### ISSUE THREAD

**Issue by 00liujj** [rafaelpadilla/Object-Detection-Metrics#16]
https://github.com/rafaelpadilla/Object-Detection-Metrics/blob/a9bb67c3663893578be8f28e46a07b9cdf14cb3a/lib/Evaluator.py#L102

**Comment by rafaelpadilla** [comment]
Dear @00liujj,

This is not a bug. I think you misunderstood an important point: The FP is accounted in the "if" in [line 107](https://github.com/rafaelpadilla/Object-Detection-Metrics/blob/a9bb67c3663893578be8f28e46a07b9cdf14cb3a/lib/Evaluator.py#L107).

The "if" in line 102 that you mentioned is used to check if the detection was already "seen" or evaluated.as a TP. A detected bounding box cannot match more than one GT. See in the [illustrated example](https://github.com/rafaelpadilla/Object-Detection-Metrics#an-ilustrated-example) image 7, that the detection *X* overlaps 2 GT. It can only be accounted by one of them.

Regards
