### ISSUE TITLE
How to calculate mAP@[0.5:0.99]?

### ISSUE THREAD

**Issue by sourabhyadav** [rafaelpadilla/Object-Detection-Metrics#165]
Is there a way to calculate mAP@[0.5:0.99] using command line?   
I see there is a parameter ```-t``` which takes single input say 0.5, is it possible to make it a for a range of values and get the mAP?  

How can I do the same?

**Comment by rafaelpadilla** [comment]
Hi @sourabhyadav ,

You would have to run the script multiple times varying the threshold.

If your detection and ground-truth files are locally, you can use [this](https://github.com/rafaelpadilla/review_object_detection_metrics) project to compute the mAP@[0.5:0.99] metric easily.

Hope that helps.
