### ISSUE TITLE
red boxes represent detections with prediction label of that class or any detections whenever it prediction is that class ?

### ISSUE THREAD

**Issue by WangRuixin93** [rafaelpadilla/Object-Detection-Metrics#166]

**Comment by rafaelpadilla** [comment]
in the example shown in the README , red boxes and green boxes are predictions and ground-truth of the same classes. Red boxes are predictions and green boxes are the ground truths.
We have to consider each class separately.

If you are evaluating "dogs" you should be looking at only predictions and ground-truths of "dogs"

Hope that answers your doubt.

**Comment by WangRuixin93** [comment]
that answered my doubt perfectly，because in many introductions about AP I've ever read, this point is ignored. Thanks!
