### ISSUE TITLE
incorrect equation

### ISSUE THREAD

**Issue by karl-gardner** [rafaelpadilla/Object-Detection-Metrics#167]
Hello Rafael,

I don't believe the equation is correct for 11 point interpolation but I could be wrong. If you think about it the sum in the AP formula would be divided by 10 not 11 so wouldn't the correct term before the sum be: 1/(11-1). Because the width of every step in the 11 points is only 0.1 not 0.09 as you currently have. This would affect the final average precision value:

![image](https://user-images.githubusercontent.com/91646805/170778943-0b57010f-3b53-4ea6-9952-f5e95d65f331.png)

Let me know if this makes sense or if I am wrong on this.

Thanks,

Karl Gardner

**Comment by rafaelpadilla** [comment]
Hi @karl-gardner ,

Thank you for your message.

The equation is correct. Note that the summation considers the recall points:
![image](https://user-images.githubusercontent.com/31217453/171055421-49a6a91d-80d4-4b31-b33e-19afb38e2ce3.png)

Note that the plot does consider all 11 points (in red), which are in those positions: {0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9. 1}

Check detailed explanation in [this](https://github.com/rafaelpadilla/review_object_detection_metrics/blob/main/published_paper.pdf) paper pages 10 and 11 specially subsection 4.2.1. "Actually the N-point interpolation as defined by Equation (11) computes an AP value which is equal to the value computed by the Riemann integral in Equation (9) multiplied by (N−1)/N ."

Hope that helps.

**Comment by karl-gardner** [comment]
Hello @rafaelpadilla

My apologies for saying it was an incorrect equation then. Thanks for the explanation. I have read the sections of the paper you referenced. In the paper you say: "Actually the N-point interpolation as defined by Equation (11) computes an AP value which is equal to the value computed by the Riemann integral in Equation (9) multiplied by (N−1)/N ."   However, in the paper you say: "and thus the expression for AP becomes (11)".  So shouldn't equation (9) and equation (11) be equal then? Afterall they are both equations for AP right?

Thanks,

Karl Gardner

**Comment by rafaelpadilla** [comment]
Hi @karl-gardner 

"Equation 9" and "Equations 11 together with Equation 10" represent the same thing.

Note that **Equation 9 is the generic AP form**, which considers Rr(0) = 1 and Rr(K+1) = 0 (initial and last recalls). Equation 11 is its particular form for the N-Point interpolation approach.

If you want to apply the N-point interpolation (N=11 produces 11-point interpolation), Equation 9 becomes Equations 10 and 11. If you want to apply all-point interpolation, use Equation 9 (see that it uses the same values as Equation 12). :)
