### ISSUE TITLE
Clarification for True Negatives

### ISSUE THREAD

**Issue by nekulkarni** [rafaelpadilla/Object-Detection-Metrics#18]
In the README the following is said about True Negatives: 

> Does not apply. It would represent a corrected misdetection. In the object detection task there are many possible bounding boxes that should not be detected within an image. Thus, TN would be all possible bounding boxes that were corrrectly not detected (so many possible boxes within an image). That's why it is not used by the metrics.

Can we cite a (formal enough) source for this information? I tried searching an evidence to support these statements but I couldn't find any solid support. 

Thanks so much.

**Comment by rafaelpadilla** [comment]
Dear @nekulkarni ,

I will try to explain it with other words:

True negatives by definition means  *the result that are correctly negative* or *the number of correct rejection*.
In the case of object detection using the approach we do, *the generic detector is not restricted.* Therefore, *it could detect an object in all possible regions of the image in all possible sizes.* As the image size is limited, the number of possible bounding boxes is finite. You could of course, find the amount of the True Negative bounding boxes if you want, but for the mAP you don't need it, once we are using only *recall* and *precision* (and they do not require the amount of TN).

Find in [this](https://www.cs.auckland.ac.nz/~rklette/TeachAuckland.html/775/pdfs/D28-Detection1.pdf) presentation some of what I have just told you (Slides 5 and 24). Also, if you google something like "true negatives in object detection" you might find some formal references.

If this is what you are looking for you, please, close this issue. And also, please, share here with us if you find other references. :)

Regards.

**Comment by nekulkarni** [comment]
@rafaelpadilla Thank you so much for the pointer and for your explanation. That answers my question.
