### ISSUE TITLE
image3 G iou ?

### ISSUE THREAD

**Issue by hnothing2016** [rafaelpadilla/Object-Detection-Metrics#181]
in example image3 G
groundtruths：person 123 30 49 44 
detections：person .18 109 15 77 39

iou = 1176 / 3983 = 0.2952548   

iou < 30% but got TP

**Comment by EMalagoli92** [comment]
@hnothing2016 Because the repository's iou function for your example returns 0.30339.
For me too, it should be 0.2952548.
