### ISSUE TITLE
getting threshold values of confidence score  which recall/precision calculated 

### ISSUE THREAD

**Issue by amor-volastra** [rafaelpadilla/Object-Detection-Metrics#182]
Hi, 
I was wondering if there is anyway to get the threshold values when using evaluator.PlotPrecisionRecallCurve. I can see it returns vectors of recalls and precisions for each class. Just wondering if there is any way to get the threshold values on confidence scores corresponding to those recalls and precisions.

Thanks,

**Comment by raider377** [comment]
@amor-volastra  Hi, did you manage to get the threshold values? I see it as a sorted list of thresholds as shown in the example table.

**Comment by amor-volastra** [comment]
@raider377 I didn't and I don't think the current version of codes return the threshold values for calculated precision and recall. Look here: https://github.com/rafaelpadilla/Object-Detection-Metrics/blob/master/lib/Evaluator.py#L178
