### ISSUE TITLE
'NoneType' object is not subscriptable when execute the example in readme

### ISSUE THREAD

**Issue by yqtianust** [rafaelpadilla/Object-Detection-Metrics#19]
Hi,

First of all, thanks for your tools!

I want to execute the example. I just git clone the project and then type:
 `python3 pascalvoc.py`

I got a img: (different with your image)

![image](https://user-images.githubusercontent.com/41743566/46650597-afa07f00-cbcf-11e8-9500-b95c5488eae6.png)

After I closed this img,

I got error like this:
```
Traceback (most recent call last):
  File "pascalvoc.py", line 328, in <module>
    cl = metricsPerClass['class']
TypeError: 'NoneType' object is not subscriptable
```

The result.txt has content:
```
Object Detection Metrics
https://github.com/rafaelpadilla/Object-Detection-Metrics


Average Precision (AP), Precision and Recall per class:
```

Any suggestion?

**Comment by ljpadam** [comment]
I add the follow code on the 232nd line in lib/Evaluator.py
`    
        return result`

**Comment by yqtianust** [comment]
@ljpadam Thank you! 
I add `return result` in lib/Evaluator.py. I got the result. But the AP is still 2.2%, using the given ground truth and detection result. I am not sure where is the problem. Or the 2.22% is correct answer for given data?

**Comment by yqtianust** [comment]
Dear @rafaelpadilla 

Thanks! It works now!

Thanks both of you. @ljpadam @rafaelpadilla 

Have a good day.
