### ISSUE TITLE
mAP is 0 for all the classes detected

### ISSUE THREAD

**Issue by Art31** [rafaelpadilla/Object-Detection-Metrics#26]
Hi Rafael,

I am pretty sure I followed all the instructions properly but still I can't get another result rather then 0 mAP for all my classes. I am attaching the detection and groundtruth files and the csvs that I used to generate the txt files. 

I issued the following command as my boxes are in the configuration <left> <top> <right> <bottom>

python pascalvoc.py -gt groundtruths_blindenhund_test -det detections_blindenhund_test -gtformat xyrb -detformat xyrb

Really appreciate the help given.

[csvs with the boxes.zip](https://github.com/rafaelpadilla/Object-Detection-Metrics/files/2545196/csvs.with.the.boxes.zip)
[detections_blindenhund_test.zip](https://github.com/rafaelpadilla/Object-Detection-Metrics/files/2545190/detections_blindenhund_test.zip)
[groundtruths_blindenhund_test.zip](https://github.com/rafaelpadilla/Object-Detection-Metrics/files/2545191/groundtruths_blindenhund_test.zip)

**Comment by rafaelpadilla** [comment]
Dear @Art31 ,

In your filtered_groundtruth_test.csv I notice something strange. The first row, for instance has: **bottom = 330, left = 121, top = 584, right = 768**

I'm reading it as: **x1 = 121, y1  = 584, x2 = 768, y2 = 330**

How can the bottom coordinate (y2) be less than the top coordinate (y1)? It happens in many (if not all) your bounding boxes.

Please, check:

1) You should take the origin of your image (0,0) as being the upper left corner.
2) As you are using the parameters `-gtformat xybr` and `-detformat xyrb`, your text files must be in the format: `<filename> <confidence> <left> <top> <right> <bottom>`

Please, close this issue if it solves your problem.

**Comment by Art31** [comment]
You are right, it was my mistake, my apologies. Thank you for the help!
