### ISSUE TITLE
is COCO metric coming?

### ISSUE THREAD

**Issue by OlofHarrysson** [rafaelpadilla/Object-Detection-Metrics#28]
Hello, I really think standardized metrics are needed for OD, nice work.

Are there plans of expanding the project to include the COCO metric?

**Comment by rafaelpadilla** [comment]
Dear @OlofHarrysson,

Thanks for your interest. :)

Yes. I have plans to expand it to other metrics. Actually I have already started the development of the COCO metrics, but haven't finished it yet. I've been busy with other projects and had to put the COCO metrics aside for a while.

But thanks for reminding me. It is in my priority list. I know this is an important feature that can benefit many users.

Regards,
Rafael
