### ISSUE TITLE
why the code is wrong

### ISSUE THREAD

**Issue by HoldYourFire** [rafaelpadilla/Object-Detection-Metrics#30]
I opened the project in pycharm 2017.3(community),but there are several red lines below the code.Does anyone have the same situation as me?

**Comment by rafaelpadilla** [comment]
Dear @HoldYourFire ,

The code is not wrong. It is designed to be used with command line as written in the (instructions)[https://github.com/rafaelpadilla/Object-Detection-Metrics#how-to-use-this-project].
