### ISSUE TITLE
mAP on COCO YoloV3 Paper

### ISSUE THREAD

**Issue by ydixon** [rafaelpadilla/Object-Detection-Metrics#31]
@rafaelpadilla First, Thanks for creating this repository. Excellent code and well explained.

I was wondering by any chance you tried running this repo against detections obtained through YoloV3 COCO with official weights loaded. I'm only getting `mAP@0.50: 40%` compared to the advertised `mAP@0.50: 55%` on the paper. What `**nms/confidence/iou**` threshold should be set in order to get proper mAP as stated on the paper? 

![mAP](https://camo.githubusercontent.com/a901864a2e44f54dd6a15dc2590d0b54761d1b4a/68747470733a2f2f6873746f2e6f72672f776562742f70772f7a642f306a2f70777a64306a623967377a6e745f646273797739717a626e7674692e6a706567)

**Comment by rafaelpadilla** [comment]
Dear @ydixon ,

I have not tried to reproduce the YOLO v3 results published on the paper. The IOU used is 50% as in the PASCAL VOC metric. But it is necessary to check on the paper the NMS used.

If I am not mistaken, [YOLO v3 page](https://pjreddie.com/darknet/yolo/) might have the trained weights to reproduce the results.

Regards

**Comment by ydixon** [comment]
@rafaelpadilla Thanks for getting back to me.  
I've written a few simple python scripts to convert results generated from [AlexeyAB/darknet](https://github.com/AlexeyAB/darknet) to formats usable by both pycocotools and this repo. Interestingly, the mAP values from both repo are very close sitting at 0.530 and 53.4%. So I'm guessing the problem lye within somewhere else. I'll let you know if I find out more.

![map_0 5iou_darknet](https://user-images.githubusercontent.com/22487836/50642471-3afa9800-0fa6-11e9-89da-bb8fb294b863.png)

`
AP: 73.43% (aeroplane)  
AP: 15.97% (apple) 
AP: 31.12% (backpack)  
AP: 31.64% (banana)  
AP: 51.75% (baseball_bat)  
AP: 49.85% (baseball_glove)  
AP: 78.70% (bear)  
AP: 69.22% (bed)
AP: 33.26% (bench)
AP: 50.93% (bicycle)
AP: 46.00% (bird)
AP: 47.34% (boat)
AP: 16.65% (book)
AP: 43.80% (bottle)
AP: 48.90% (bowl)
AP: 30.81% (broccoli)
AP: 81.79% (bus)
AP: 48.09% (cake)
AP: 60.59% (car)
AP: 22.00% (carrot)
AP: 77.35% (cat)
AP: 42.31% (cell_phone)
AP: 42.51% (chair)
AP: 73.79% (clock)
AP: 44.61% (cow)
AP: 49.41% (cup)
AP: 45.60% (diningtable)
AP: 78.24% (dog)
AP: 40.49% (donut)
AP: 79.89% (elephant)
AP: 80.86% (fire_hydrant)
AP: 37.61% (fork)
AP: 73.14% (frisbee)
AP: 86.74% (giraffe)
AP: 9.09% (hair_drier)
AP: 21.43% (handbag)
AP: 77.39% (horse)
AP: 40.34% (hot_dog)
AP: 68.82% (keyboard)
AP: 43.40% (kite)
AP: 29.95% (knife)
AP: 71.92% (laptop)
AP: 69.98% (microwave)
AP: 66.37% (motorbike)
AP: 70.41% (mouse)
AP: 32.29% (orange)
AP: 49.43% (oven)
AP: 54.77% (parking_meter)
AP: 71.93% (person)
AP: 58.52% (pizza)
AP: 43.61% (pottedplant)
AP: 72.45% (refrigerator)
AP: 49.44% (remote)
AP: 45.99% (sandwich)
AP: 38.44% (scissors)
AP: 56.43% (sheep)
AP: 60.97% (sink)
AP: 69.94% (skateboard)
AP: 37.55% (skis)
AP: 48.45% (snowboard)
AP: 56.02% (sofa)
AP: 24.63% (spoon)
AP: 62.04% (sports_ball)
AP: 78.23% (stop_sign)
AP: 48.00% (suitcase)
AP: 64.26% (surfboard)
AP: 58.62% (teddy_bear)
AP: 71.64% (tennis_racket)
AP: 52.70% (tie)
AP: 19.82% (toaster)
AP: 75.81% (toilet)
AP: 34.84% (toothbrush)
AP: 51.36% (traffic_light)
AP: 81.07% (train)
AP: 48.85% (truck)
AP: 75.88% (tvmonitor)
AP: 57.70% (umbrella)
AP: 49.23% (vase)
AP: 49.24% (wine_glass)
AP: 79.87% (zebra)

mAP: 53.54%`

**Comment by rafaelpadilla** [comment]
Dear @ydixon ,

I know what you mean. This little difference among the official tools (like COCO, VOC PASCAL) and 3rd party projects that motivated me to create our project. After understanding exactly how the official codes implement the metrics, I was able to reproduce exactly their results.

I have been busy with other projects and have not published the COCO metrics. Meanwhile, I suggest you to use the official COCO implementation to report your results. Once I publish the COCO metrics, I can guarantee that our results will be identical to the official metrics.

Best regards
