### ISSUE TITLE
Possible bug - Evaulator.py

### ISSUE THREAD

**Issue by mils33** [rafaelpadilla/Object-Detection-Metrics#33]
Firstly, your project is awesome!
Why you cut out last element from mrec in ElevenPointInterpolatedAP (Evaluator.py at line 332)?
`argGreaterRecalls = np.argwhere(mrec[:-1] >= r)`
You lose one recall point, why?
I think it should be `argGreaterRecalls = np.argwhere(mrec[:] >= r)`

This can reduce map especially for small set of detections.

**Comment by rafaelpadilla** [comment]
Dear @mils33,

You are right, the last recall point was left out. All elements are being verified now.

Thanks for your message!
