### ISSUE TITLE
Sort FP and TP images in result

### ISSUE THREAD

**Issue by VinayakaPrabhu** [rafaelpadilla/Object-Detection-Metrics#34]
Hi @rafaelpadilla 

Thank you for the extremely helpful repo.

Is there any way to sort the FP and TP images in results ?

This will be helpful. Thank you.

**Comment by rafaelpadilla** [comment]
Dear @VinayakaPrabhu,

The FP and TP are not the images, but the bounding boxes detected in each image.

It is not implemented. One could modify the function [GetPascalVOCMetrics](https://github.com/rafaelpadilla/Object-Detection-Metrics/blob/master/lib/Evaluator.py#L24) providing the desired sorting.

Regards,
Rafael
