### ISSUE TITLE
Detection files left top width height

### ISSUE THREAD

**Issue by shahrukh131** [rafaelpadilla/Object-Detection-Metrics#35]
how can i find (left top width height) from detection images?

**Comment by rafaelpadilla** [comment]
Dear @shahrukh131,

I don't know if I understood your question. But the bounding boxes (left, top, width and height) must be provided by your detector. This repo only evaluates the detections you provide.

You can use any object detector to generate the bounding boxes for you (YOLO, Faster R-CNN, R-FCN, FPN, etc).

Best regards.

**Comment by shahrukh131** [comment]
[https://github.com/rafaelpadilla/Object-Detection-Metrics#create-your-detection-files](url)
for this step how i can find  <left> <top> <right> <bottom> from the detected images?
![53289811_155971241993846_7332497600865632256_n](https://user-images.githubusercontent.com/31450736/53883418-26d52480-4043-11e9-98fa-f236f6b10c9a.png)
supoose from this image how can i find <left> <top> <right> <bottom> ?

**Comment by rafaelpadilla** [comment]
@shahrukh131,

The bounding box coordinates for your detections (left top right bottom) is given by your object detector. As I mentioned to you in the previous message, you can use any object detector you want to find those objects for you (YOLO, Faster R-CNN, R-FCN, FPN, etc).

The ground truth coordinates are given either by your labeled database or you can manually get those coordinates.

I hope I could answer your question properly.
