### ISSUE TITLE
Output multiple results on same plot

### ISSUE THREAD

**Issue by kevinisbest** [rafaelpadilla/Object-Detection-Metrics#37]
Thank you for the useful measurement tool!
Is it possible that input one and more prediction folders and plot them on the same picture?

**Comment by rafaelpadilla** [comment]
Dear @kevinisbest,

On the current version it is not possible. You have to put all detection files in a unique folder and it outputs a single plot.

Note that the function [GetPascalVOCMetrics](https://github.com/rafaelpadilla/Object-Detection-Metrics/blob/master/lib/Evaluator.py#L24) returns a dictionary with all necessary data to plot the Precision-Recall curve. You could call it for many folders and gather all the results in the same plot. See how this dictionary is used by the function [PlotPrecisionRecallCurve](https://github.com/rafaelpadilla/Object-Detection-Metrics/blob/master/lib/Evaluator.py#L148) to plot the results.

Regards,
Rafael

**Comment by kevinisbest** [comment]
Thanks for your quick reply, I will try calling the function in a loop and look forward to the enhancement on multiple results!
