### ISSUE TITLE
Giving synatx error while validating the savepath

### ISSUE THREAD

**Issue by manikantarav** [rafaelpadilla/Object-Detection-Metrics#38]
Since iam new to python, i couldnot figure out , what the problem is. i had given gt files, detection files as per instructions. can you check, what can be the problem. i wasted one day for this error. still could not find. help me here

########################################
$ python pascalvoc.py -gtformat xyrb or $ python pascalvoc.py
  File "pascalvoc.py", line 292
    [print(e) for e in errors]
         ^
SyntaxError: invalid syntax
################################

**Comment by rafaelpadilla** [comment]
Dear @manikantarav,

This was already discussed in [another](https://github.com/rafaelpadilla/Object-Detection-Metrics/issues/9) thread. This will happen if you are using python 2.

To make it work replace line 292 to:
```
for e in errors:
    print(e)
```

Regards,
Rafael

**Comment by manikantarav** [comment]
dear @rafaelpadilla 
Thank you reaching out very  quickly. i could resolve past issue. iam getting a different issue now. I think changing string to float for confidence. it is giving this error.
###################################
Traceback (most recent call last):
  File "pascalvoc.py", line 317, in <module>
    detFolder, False, detFormat, detCoordType, allBoundingBoxes, allClasses, imgSize=imgSize)
  File "pascalvoc.py", line 144, in getBoundingBoxes
    confidence = float(splitLine[1])
IndexError: list index out of range
#############################################

Another doubt.. is there any restriction that there should be one space(" ") between elements in text files?

**Comment by rafaelpadilla** [comment]
dear @manikantarav,

Something seems to be wrong with one of your txt files containing your ground truth detections.

Please, check it and try again.

To see which file is presenting this problem, at file pascalvoc.py, line 116 add the following code:

`for f in files:
        **print('file: %s' % f)**
        nameOfImage = f.replace(".txt", "")
        fh1 = open(f, "r")
`

Then check which of your txt file is not following the requirements as described [here](https://github.com/rafaelpadilla/Object-Detection-Metrics#create-the-ground-truth-files).

Regards,
Rafael
