### ISSUE TITLE
Converting VOC annotation format to desired format

### ISSUE THREAD

**Issue by hyejung-rachel** [rafaelpadilla/Object-Detection-Metrics#39]
Hi! I have all my annotations in XML format. I wish to evaluate a model on my own custom dataset (which do not belong to the original VOC classes). Is there a quick way to convert the annotations to the format for evaluation?

**Comment by pixx1** [comment]
Hi! 
I wrote a converter, if you could wait till tomorrow i could post it.
Greetings
pix_1

**Comment by hyejung-rachel** [comment]
> Hi!
> I wrote a converter, if you could wait till tomorrow i could post it.
> Greetings
> pix_1

Hi pix_1! Sure I can wait! Could you post the link here when it is done? Thank you!

**Comment by pixx1** [comment]
Here my solution I wrote a while ago: 

I assumed that you meant the pascal VOC format:
<details><summary>pascal voc 2012 example</summary>
<p>

```xml
<annotation>
	<folder>images</folder>
	<filename>house.jpg</filename>
	<path>/fancy_path/house.jpg</path>
	<source>
		<database>survey_1806</database>
	</source>
	<size>
		<width>600</width>
		<height>600</height>
		<depth>3</depth>
	</size>
	<segmented>0</segmented>
	<object>
		<name>cat_nose</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<ymin>80</ymin>
			<xmin>456</xmin>
			<ymax>161</ymax>
			<xmax>48</xmax>
		</bndbox>
	</object>
</annotation>
```
</p>
</details>

```python
from pathlib import Path
import xml.etree.ElementTree as ET
from typing import Dict


class XMLHandler:
    def __init__(self, xml_path: str or Path):
        self.xml_path = Path(xml_path)
        self.root = self.__open()

    def __open(self):
        with self.xml_path.open() as opened_xml_file:
            self.tree = ET.parse(opened_xml_file)
            return self.tree.getroot()

    def return_boxes_class_as_dict(self) -> Dict[int, Dict]:
        """
        Returns Dict with class name and bounding boxes.
        Key number is box number

        :return:
        """

        boxes_dict = {}
        for index, sg_box in enumerate(self.root.iter('object')):
            boxes_dict[index] = {"name": sg_box.find("name").text,
                                 "xmin": int(sg_box.find("bndbox").find("xmin").text),
                                 "ymin": int(sg_box.find("bndbox").find("ymin").text),
                                 "xmax": int(sg_box.find("bndbox").find("xmax").text),
                                 "ymax": int(sg_box.find("bndbox").find("ymax").text)}

        return boxes_dict


def converter(xml_files: str, output_folder: str) -> None:
    """
    Function converts pascal voc formatted files into ODM-File format

    :param xml_files: Path to folder with xml files
    :param output_folder: Path where results files should be written
    :return:
    """
    xml_files = list(Path(xml_files).rglob("*.xml"))

    for xml_index, xml in enumerate(xml_files, start=1):
        filename = f"{xml_index:09}.txt"
        filename_path = Path(output_folder) / filename
        xml_content = XMLHandler(xml)
        boxes = xml_content.return_boxes_class_as_dict()

        with open(filename_path, "a") as file:
            for box_index in boxes:
                box = boxes[box_index]
                box_content = f"{box['name']} {box['xmin']} {box['ymin']} {box['xmax']} {box['ymax']}\n"
                file.write(box_content)

    print(f"Converted {len(xml_files)} files!")

    
if __name__ == '__main__':
    XML_FOLDER = "YOUR PATH HERE"
    OUTPUT_FOLDER =  "YOUR PATH HERE"

    converter(XML_FOLDER, OUTPUT_FOLDER)

```

**Comment by hyejung-rachel** [comment]
> Here my solution I wrote a while ago:
> 
> I assumed that you meant the pascal VOC format:
> 
> pascal voc 2012 example
> ```python
> from pathlib import Path
> import xml.etree.ElementTree as ET
> from typing import Dict
> 
> 
> class XMLHandler:
>     def __init__(self, xml_path: str or Path):
>         self.xml_path = Path(xml_path)
>         self.root = self.__open()
> 
>     def __open(self):
>         with self.xml_path.open() as opened_xml_file:
>             self.tree = ET.parse(opened_xml_file)
>             return self.tree.getroot()
> 
>     def return_boxes_class_as_dict(self) -> Dict[int, Dict]:
>         """
>         Returns Dict with class name and bounding boxes.
>         Key number is box number
> 
>         :return:
>         """
> 
>         boxes_dict = {}
>         for index, sg_box in enumerate(self.root.iter('object')):
>             boxes_dict[index] = {"name": sg_box.find("name").text,
>                                  "xmin": int(sg_box.find("bndbox").find("xmin").text),
>                                  "ymin": int(sg_box.find("bndbox").find("ymin").text),
>                                  "xmax": int(sg_box.find("bndbox").find("xmax").text),
>                                  "ymax": int(sg_box.find("bndbox").find("ymax").text)}
> 
>         return boxes_dict
> 
> 
> def converter(xml_files: str, output_folder: str) -> None:
>     """
>     Function converts pascal voc formatted files into ODM-File format
> 
>     :param xml_files: Path to folder with xml files
>     :param output_folder: Path where results files should be written
>     :return:
>     """
>     xml_files = sorted(list(Path(xml_files).rglob("*.xml")))
> 
>     for xml_index, xml in enumerate(xml_files, start=1):
>         filename = f"{xml_index:09}.txt"
>         filename_path = Path(output_folder) / filename
>         xml_content = XMLHandler(xml)
>         boxes = xml_content.return_boxes_class_as_dict()
> 
>         with open(filename_path, "a") as file:
>             for box_index in boxes:
>                 box = boxes[box_index]
>                 box_content = f"{box['name']} {box['xmin']} {box['ymin']} {box['xmax']} {box['ymax']}\n"
>                 file.write(box_content)
> 
>     print(f"Converted {len(xml_files)} files!")
> 
>     
> if __name__ == '__main__':
>     XML_FOLDER = "YOUR PATH HERE"
>     OUTPUT_FOLDER =  "YOUR PATH HERE"
> 
>     converter(XML_FOLDER, OUTPUT_FOLDER)
> ```

Hi! The desired output format is `<class_name> <confidence> <left> <top> <right> <bottom>` or `<class_name> <left> <top> <width> <height>`. I believe it is different from `<class_name> <xmin> <ymin> <xmax> <ymax>` >.<

**Comment by pixx1** [comment]
>Hi! The desired output format is <class_name> <confidence> <left> <top> <right> <bottom> or <class_name> <left> <top> <width> <height>. I believe it is different from <class_name> <xmin> <ymin> <xmax> <ymax> >.<

Why do you think it's different from the needed one?
My results with that method seems okay when I'm using "-gt xyrb -det xyrb".

**Comment by pixx1** [comment]
What i wrote is just for the ground truth... I dont know in which format your prediction is stored.

> <class_name> <confidence> <left> <top> <right> <bottom> or <class_name> <left> > <top> <width> <height>

Did you mixed up something? When you tell me the prediction Format i can may help you

**Comment by rafaelpadilla** [comment]
Dear @hyejung-rachel, please, check  @pixx1's answer.

Thanks, @pixx1 :+1:
