### ISSUE TITLE
Did you conclude differences comparing with official algorithms?

### ISSUE THREAD

**Issue by JohnLyu94** [rafaelpadilla/Object-Detection-Metrics#41]
Hi, I really appreciate your efforts on this project. Actually, I am writing a paper of my project. I would like to use your code to validate my datasets. Could you please add some comparison and how to cite this project?

**Comment by rafaelpadilla** [comment]
Dear @JohnLyu94,

You can use the [DOI 10.5281/zenodo.2554189](https://zenodo.org/record/2554189#.XKY6_XX0nCI) to reference this repository mentioning the link for the project. Below some extra information you may need.

Author: Rafael Padilla (Padilla, Rafael)
Affiliation: Signal Multimedia and Telecommunications Laboratory (SMT), COPPE, UFRJ-RJ
Project: Object Detection Metrics
Publication date: January 31, 2019

Regards,
Rafael
