### ISSUE TITLE
About fixed size images and False negative (FN)?

### ISSUE THREAD

**Issue by ibrahimLearning** [rafaelpadilla/Object-Detection-Metrics#45]
@rafaelpadilla Thank very much for your contribution. Maybe your code is for fixed size image, like
`......CoordinatesType.Absolute, (200, 200),........`
would you explain please for different size?

How can I calculate FN (false negative), would you suggest me please?

Thanks

**Comment by rafaelpadilla** [comment]
Dear @ibrahimLearning,

You are right. The example was done for 200x200 images.

For images with different sizes you should change these values either in the code (as you mentioned) or in the .txt files.

The FN (false negative) represents the ground truth objects that were not detected.

As TP + FN = all ground truth objects
then **FN = all ground truth objects - TP**

Best regards,
Rafael
