### ISSUE TITLE
CoordinateTypes.Absolute Not defined

### ISSUE THREAD

**Issue by jaideep11061982** [rafaelpadilla/Object-Detection-Metrics#48]
Hi rafael
I get an error at the point of procedure def parameter list
where we referring CoordinatesTypes' class attribute. 
I think we should put utils first
kaggle/working/Object-Detection-Metrics/lib/Evaluator.py in <module>()
     16 import numpy as np
     17 
---> 18 from BoundingBox import *
     19 from BoundingBoxes import *
     20 from utils import *

/kaggle/working/Object-Detection-Metrics/lib/BoundingBox.py in <module>()
      2 
      3 
----> 4 class BoundingBox:
      5     def __init__(self,
      6                  imageName,

/kaggle/working/Object-Detection-Metrics/lib/BoundingBox.py in BoundingBox()
     10                  w,
     11                  h,
---> 12                  **typeCoordinates=CoordinatesType.Absolute,**
     13                  imgSize=None,
     14                  bbType=BBType.GroundTruth,

**Comment by rafaelpadilla** [comment]
Dear @jaideep11061982 ,

If you import utils first, does it solve your problem?
