### ISSUE TITLE
Question - Is mAP of 2.22% the "correct" value for example in Sample_2 folder?

### ISSUE THREAD

**Issue by HamsterHuey** [rafaelpadilla/Object-Detection-Metrics#50]
Hi. Thanks a lot for this repo. I just wanted to verify/test the code with the example you provide in the Sample2 folder. When I run the code with an IOU threshold of 0.5, I get a mAP of 2.22%. Is this correct? 

It just seems to be a very low value for an example which I would have assumed would have perhaps had some more overlap between ground-truth and targets. I just wanted to double-check that this value is expected and correct as I couldn't find anything in the documentation about the expected mAP for class 'object' in the example folder.

Thanks!

**Comment by rafaelpadilla** [comment]
Dear @HamsterHuey,

Yes, in sample 2 if you set the threshold to 0.5 and keep the `method=MethodAveragePrecision.ElevenPointInterpolation`, you will get a mAP of 2.22%.

 [These](https://github.com/rafaelpadilla/Object-Detection-Metrics/raw/master/aux_images/samples_1_v2.png) are the detections in sample 2. Below I give you a list of the IOUs for each detection bounding box within each image. The coordinates will help you localize them.

image 00001
dect => (124.0, 9.0, 173.0, 76.0) IOU: 0.00 (FP)
dect => (5.0, 67.0, 36.0, 115.0) IOU: 0.02 (FP)
dect => (119.0, 111.0, 159.0, 178.0) IOU: 0.47 (FP)

image 00002
dect => (19.0, 18.0, 62.0, 53.0) IOU: 0.00 (FP)
dect => (64.0, 111.0, 128.0, 169.0) IOU: 0.24 (FP)
dect => (26.0, 140.0, 86.0, 187.0) IOU: 0.49 (FP)

image 00003
dect => (109.0, 15.0, 186.0, 54.0) IOU: 0.30 (FP)
dect => (86.0, 63.0, 132.0, 108.0) IOU: 0.03 (FP)
dect => (160.0, 62.0, 196.0, 115.0) IOU: 0.04 (FP)
dect => (18.0, 148.0, 58.0, 192.0) IOU: 0.00 (FP)
dect => (105.0, 131.0, 152.0, 178.0) IOU: 0.57 (TP)

image 00004
dect => (28.0, 68.0, 70.0, 135.0) IOU: 0.11 (FP)
dect => (87.0, 89.0, 112.0, 128.0) IOU: 0.01 (FP)
dect => (83.0, 28.0, 111.0, 54.0) IOU: 0.05 (FP)
dect => (10.0, 155.0, 70.0, 181.0) IOU: 0.00 (FP)

image 00005
dect => (29.0, 131.0, 101.0, 160.0) IOU: 0.35 (FP)
dect => (50.0, 38.0, 78.0, 84.0) IOU: 0.32 (FP)
dect => (95.0, 11.0, 148.0, 39.0) IOU: 0.02 (FP)
dect => (29.0, 163.0, 101.0, 192.0) IOU: 0.18 (FP)

image 00006
dect => (17.0, 155.0, 46.0, 190.0) IOU: 0.02 (FP)
dect => (43.0, 48.0, 117.0, 86.0) IOU: 0.28 (FP)
dect => (95.0, 110.0, 120.0, 152.0) IOU: 0.05 (FP)

image 00007
dect => (16.0, 20.0, 117.0, 108.0) IOU: 0.39 (FP)
dect 00007 => (33.0, 116.0, 70.0, 165.0) IOU: 0.03 (FP)

Note how bad the IOUs are. For the threshold set to 0.5 only 1 detection will be signed to TP.

Please, consider closing this issue if your question has been properly solved.

Best regards,
Rafael

**Comment by HamsterHuey** [comment]
Thanks a lot @rafaelpadilla . That makes sense. I'll close the issue.
