### ISSUE TITLE
No confidence score for the predicted boxes

### ISSUE THREAD

**Issue by pordeli** [rafaelpadilla/Object-Detection-Metrics#51]
I have ground truth boxes and predicted boxes from YOLO and DPM and Openpose algorithms. Their format is [ x y w h] and I do not have the confidence scores. Is it possible to use your python code for getting the precision and recall and the curve? I get the below error:
Metrics-master/lib/BoundingBox.py", line 45, in __init__
    'For bbType=\'Detection\', it is necessary to inform the classConfidence value.')
OSError: For bbType='Detection', it is necessary to inform the classConfidence value.

**Comment by rafaelpadilla** [comment]
Dear @pordeli ,

No. You need the confidence scores to evaluate your detections.

Best regards,
Rafael

**Comment by pordeli** [comment]
Thanks for your reply. As long as I do not have the scores do you know a kind of code that I can use to get precision and recall and the curve for my 100 frames of the video?

**Comment by Ibmaria** [comment]
hello ,
I try to evaluate the model with my own dataset .Can you tell me how to get the box coordinates detected  in this format 
<class_name> <confidence> <left> <top> <right> <bottom> for evaluation .Thanks

**Comment by rafaelpadilla** [comment]
@pordeli ,

Due to the behavior of the metric we apply you will need the confidences. I do not know any other code that you could use.

**Comment by rafaelpadilla** [comment]
@Ibmaria ,

For the detections you need to apply an object detector, such as YOLO, Faster R-CNN, Fast R-CNN, etc. They will provide the detection bounding boxes, classes and confidences.

**Comment by Ibmaria** [comment]
@rafaelpadilla 

For the model i use ssd mobilenet ,
for evaluation you said  that to create 2 folders for ground truth and detection .How did you create detection file in the format class_name, confidence left top right bottom .I can not save them in txt format .How to save them like ground truth.Thanks for advance

**Comment by rafaelpadilla** [comment]
@Ibmaria ,

I never worked with mobilenet, so I dont know its output format. But you should get its output and convert it to the required format.

**Comment by Ibmaria** [comment]
@rafaelpadilla 
my question is that how to convert it to the required format  with the same name 00001.txt

**Comment by rafaelpadilla** [comment]
Dear @Ibmaria ,

You will need to create a script for that. It will take your detections to convert from the format mobilenet provides to the [format and name required](https://github.com/rafaelpadilla/Object-Detection-Metrics#create-your-detection-files).

Could you show me the detections format given by mobilenet?

**Comment by Ibmaria** [comment]
@rafaelpadilla 
can you show me rather your script.I will try to understand  and adapt it to mine.Or your email i will send ssen you my code .Thanks in advance

**Comment by Ibmaria** [comment]
@rafaelpadilla 
Finally i did .Thanks

**Comment by rafaelpadilla** [comment]
@Ibmaria ,

I do not have a script for that. If you provide the output format of the mobilenet, I might be able to help you.

**Comment by rafaelpadilla** [comment]
@Ibmaria ,

Was your problem solved?

**Comment by Ibmaria** [comment]
@rafaelpadilla 
yes i did it .Thanks
