### ISSUE TITLE
Assertion error

### ISSUE THREAD

**Issue by rohith513** [rafaelpadilla/Object-Detection-Metrics#53]
I have groundtruth and detections files in the required format. But it get the below error.

I changed the default values of gtformat and detformat to 'xyrb' as my data is in the format
<left> <top> <right> <bottom>

Traceback (most recent call last):
  File "pascalvoc.py", line 331, in <module>
    showGraphic=showPlot)
  File "/home/rotu/Downloads/final/keras-frcnn-master/metrics/lib/Evaluator.py", line 187, in PlotPrecisionRecallCurve
    results = self.GetPascalVOCMetrics(boundingBoxes, IOUThreshold, method)
  File "/home/rotu/Downloads/final/keras-frcnn-master/metrics/lib/Evaluator.py", line 106, in GetPascalVOCMetrics
    iou = Evaluator.iou(dects[d][3], gt[j][3])
  File "/home/rotu/Downloads/final/keras-frcnn-master/metrics/lib/Evaluator.py", line 390, in iou
    assert iou >= 0
AssertionError

**Comment by rafaelpadilla** [comment]
Dear @rohith513 ,

Could you please share your detection and gt files so I can take a look at them? What is the command with arguments you are using? `python vocpascal.py [your arguments]`

Regards

**Comment by rohith513** [comment]
Hello, Thanks for the reply.
gtfile:
[0000012.txt](https://github.com/rafaelpadilla/Object-Detection-Metrics/files/3280480/0000012.txt)

detfile:
[0000012.txt](https://github.com/rafaelpadilla/Object-Detection-Metrics/files/3280499/0000012.txt)

When I created det and gt files again in the format (<classname> <left><top><width><height>), it was working fine.

**Comment by raj-shah14** [comment]
I had a similar issue, in Evaluator.py script under lib directory, i changed the following function definition after reading [here](https://www.pyimagesearch.com/2016/11/07/intersection-over-union-iou-for-object-detection/)
`@staticmethod
    def _getIntersectionArea(boxA, boxB):
        xA = max(boxA[0], boxB[0])
        yA = max(boxA[1], boxB[1])
        xB = min(boxA[2], boxB[2])
        yB = min(boxA[3], boxB[3])
        # intersection area
        return (xB - xA + 1) * (yB - yA + 1)`
Change the return to the following
`return max(0,xB - xA + 1) * max(0,yB - yA + 1)`

**Comment by rafaelpadilla** [comment]
@rohith513 ,

I see that the files you shared have values separated by comma. They should be separated by single spaces  " ". Have you tried that?

**Comment by rohith513** [comment]
@rafaelpadilla 
Hello, I generated my groundtruths and detection data with values separated by comma. So, I changed your code from line.split() to line.split(","). This will split when it sees commas instead of spaces. But I think this has nothing to do with the above error. Because "xywh" format works. But thanks for your work. Hope this will be solved soon.

And also do we calculate mAP during validation or testing. Or is it only during testing?

**Comment by rafaelpadilla** [comment]
@rohith513 ,

Yes, you could use mAP during your validation. If, for example, you want to determine the best number of epochs to stop your training (early-stop), you could separate part of your dataset for validation and apply the mAP in it.

**Comment by rohith513** [comment]
@rafaelpadilla 
Great. And thank you for the clear explanation of mAP 🙏

**Comment by fauzanzaid** [comment]
@rohith513 What format are you using for the values?
If you are using the `xyrb` format, then you need to switch the second and fourth columns in your file so that they correspond to top and bottom values. Top values should be greater than bottom values. The `_getIntersectionArea()` returns a negative result if the ordering is incorrect and causes the assertion error.
