### ISSUE TITLE
Using same metric with another repo, got same number of TF and FP but mAP is different 

### ISSUE THREAD

**Issue by laclouis5** [rafaelpadilla/Object-Detection-Metrics#57]
Hi,
I run your code with detections from darknet detection framework (AlexeyAB branch) using AUC mode. Your code returns the same number of TP and FP as darknet (and the same number of positive obviously) but map function but mAP is different.

With your repo:
```
maize  - mAP: 91.39 %, TP: 150, FP: 24, npos: 162
bean   - mAP: 85.93 %, TP: 151, FP: 41, npos: 171
carrot - mAP: 74.80 %, TP: 112, FP: 51, npos: 134
npos = 467
```

Darknet map output:
```
detections_count = 1469, unique_truth_count = 467  
name = maize,  ap = 94.02%, TP = 150, FP = 24
name = bean,   ap = 91.14%, TP = 151, FP = 41
name = carrot, ap = 79.26%, TP = 112, FP = 51
```

I can't figure out in which repo the error is hiding, if there is one. Have some idea?

**Comment by rafaelpadilla** [comment]
Dear @laclouis5 ,
 
Thanks for your message. 

I have not many details about the metrics implemented by non official codes besides the VOC Pascal official code. 

Which method does the darknet implementation that you are using applies: 11-point interpolation or Interpolating all points? In my repo you can choose between them. Maybe the difference is in the method you are using.

Are you sure the mentioned implementation uses the official VOC Pascal reference? They may use other metrics like the coco mAP (see details [here](http://cocodataset.org/#detection-eval)).

**Comment by laclouis5** [comment]
Thank you for your response,

I tried another [repo](https://github.com/Cartucho/mAP) that gives same results as yours so I guess Darknet implementation is different (while claiming using the official Pascal VOC).

I choose all-points interpolation on all repos but I also tried 11-points.
