### ISSUE TITLE
Packaging as a pip modules

### ISSUE THREAD

**Issue by andreydung** [rafaelpadilla/Object-Detection-Metrics#58]
Thanks for the useful library, this is much needed!

I'm wondering if you would be interested in converting this to a pip module? So that other users would just have to `import object_detection_metrics` to run your code, and avoid shipping your code along the repo.

We could push a PR for this.

**Comment by rafaelpadilla** [comment]
Dear @andreydung ,

Thanks for your message. Yes, it would be a nice opportunity to make this code useful to other people.

I have a work in progress in this current repo to chang some variables names and some optimizing some parts of the code. I would like to finish that before adding it to pip.

Do you have experience on building pip modules?

**Comment by andreydung** [comment]
@rafaelpadilla yes just need to wrap into a module, and then add a `setup.py` file (similar to scikit-learn). We'll be waiting for the optimization until converting to pip then.

**Comment by malpunek** [comment]
@rafaelpadilla Any progress? Do you need any help?

IMHO, the pip package is a must. You've done some excellent hard work, releasing the pip package is the small step separating this project from becoming the industry standard.

**Comment by SJBertram** [comment]
Is it possible to re-open this? Have the necessary changes from August 2019 been made so that it could be packaged as a module? The documentation on this repo is very thorough and it's still maintained, so it would be great to be able to integrate these functions into other code to calculate the statistics and then do further processing on them.

**Comment by rafaelpadilla** [comment]
How can we proceed to make it available into a pip package?

Who has experience on generating pip packages that could help us on that? Any volunteer?
