### ISSUE TITLE
compare coocapi with your metric result

### ISSUE THREAD

**Issue by wucj123** [rafaelpadilla/Object-Detection-Metrics#59]
why are your metric results deferent from cocoapi metric result? Iou=0.5, coco metric result is 78.1%, while your metric result is 84.42%, i metric 6classes.

**Comment by rafaelpadilla** [comment]
Dear @wucj123,

This repository should be compared to PASCAL VOC metrics.

Our intention is to publish the COCO metrics in the future.

best regards

**Comment by wucj123** [comment]
> Dear @wucj123,
> 
> This repository should be compared to PASCAL VOC metrics.
> 
> Our intention is to publish the COCO metrics in the future.
> 
> best regards

@rafaelpadilla thank you for your reply. Do u mean COCO AP@0.5 is deferent from your metric result when IOU thershold is 0.5. I'm looking forward to your COCO metrics.

**Comment by rafaelpadilla** [comment]
@wucj123 ,

According to cocos [documentation](http://cocodataset.org/#detection-eval), COCO AP@0.5 should be the same as PASCAL VOC, which is the one implemented here with threshold 0.5.

I just need to check if COCOs AP@0.5 uses the interpolation of 11 points or all points.

Regards
