### ISSUE TITLE
FN and FP double count when IoU< 0.5?

### ISSUE THREAD

**Issue by TiongSun** [rafaelpadilla/Object-Detection-Metrics#60]
![Untitled](https://user-images.githubusercontent.com/20927562/63265804-03d0c100-c2c1-11e9-9abc-eccd74657847.png)

I am interested in calculating the F1 score, sensitivity and specificity. I wonder for the example above, does it mean that when the prediction has IoU < 0.5, it will be counted as both FN and FP?

If so, doesnt the output punish IoU < 0.5 twice and affect the accuracy of F1, sensitivity and specificity calculation?

Any advice is appreciated. Thank you!

**Comment by rafaelpadilla** [comment]
Dear @TiongSun ,

You should also consider the confidence of the detections. I believe you have already filtered your detections by a confidence score. In your example, the only prediction you have (in red) should be considered a False Positive (FP). 

Note that:
**Precision = TP / (all correct detections)** = percentage of correct positive predictions.
**Recall = TP / (all ground truths)** = the percentage of TP detected among all relevant ground truths.

Therefore, in your example: Precision = 0% , Recall = 0% and therefore F1-score = 0

I hope it helps.

**Comment by TiongSun** [comment]
Thank you @rafaelpadilla 
For the example above, should the results be:

TP = 0
FP = 1
TN = 0

OR 

TP = 0
FP = 1
TN = 1

?

**Comment by rafaelpadilla** [comment]
Dear @TiongSun ,

TP = 0 (your predictions detected correctly 0 objects)
FP = 1 (your predictions detected incorrectly 1 object)
FN = 2 (2 ground truths not detected)

Another way to get the False Negatives is:

You always must satisfy: **all ground truths = TP + FN**. So,
all ground truths = 2
TP = 0
therefore FN = 2

I hope it was clear.

**Comment by TiongSun** [comment]
@rafaelpadilla   It was clear and it helps! Thank you very much!
