### ISSUE TITLE
BoundingBox code error?

### ISSUE THREAD

**Issue by NgoJunHaoJason** [rafaelpadilla/Object-Detection-Metrics#62]
https://github.com/rafaelpadilla/Object-Detection-Metrics/blob/652c29762776b67505c307c506eb6437df015b0a/lib/BoundingBox.py#L136

I'm guessing the correct code is 
`det1.getConfidence() == det2.getConfidence()` 
instead of  
`det1.classConfidence == det2.classConfidenc()`

**Comment by rafaelpadilla** [comment]
@NgoJunHaoJason ,

You are right! Thank you :)

As this function is just a help function that could be used in the future, I wont make any update in the master.

Soon I will be updating the master branch with new features, and this will be corrected.

Thank you!
