### ISSUE TITLE
General Question about mAP, Object detected but wrong class?

### ISSUE THREAD

**Issue by htzmedia** [rafaelpadilla/Object-Detection-Metrics#63]
Hi I have a general Question about mAP.

If I have a detection but the class is not correct, for example, a Human is detected as a Horse.
Is this a false_negative?  IoU doesn't matter in this case, does it?

**Comment by rafaelpadilla** [comment]
Dear @htzmedia,

You need to compare only the detections and groundtruths of the same classes. Therefore, in your example, you can only compare human detections with human groundtruth and horses detections with horse groundtruths.

In practice you go over your detections each class (horse, human, dog ... ) at a time. 

I hope it helped.
