### ISSUE TITLE
Object detection API metrics diff your metrics

### ISSUE THREAD

**Issue by opr-sergey** [rafaelpadilla/Object-Detection-Metrics#64]
Hi, Rafael!
I use Object Detection API for detection objects, and use [EvalConfig.metrics_set='pascal_voc_detection_metrics'](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/evaluation_protocols.md), but result metrics differ with yours, can this be? I evaluate all images from my eval dataset from OD TF API and yours method. From this code I tried use _method=MethodAveragePrecision.EveryPointInterpolation_ and _method=MethodAveragePrecision.ElevenPointInterpolation_. Thanks

**Comment by rafaelpadilla** [comment]
Dear @opr-sergey ,

Do you know which method they use? The interpolation on every point or the 11-point interpolation?

Could you please send me your data, so I can debug both projects and see where the difference is?

**Comment by opr-sergey** [comment]
I found my problem. 
Object detection API use max_detections_per_class=100 by default, and return 100 elems scores with bboxes accordingly. When parsing detection result for collect [detection format](https://github.com/rafaelpadilla/Object-Detection-Metrics#create-your-detection-files), I have condition
` if detection_score < threshold: continue`. 
Object detection API when measure metrics, use all score's (100). But I used score's when detection_score parameter > threshold. This was the reason for the discrepancy. Thanks a lot for your code and explanation :)

my fragment code:
```
def detect_coords_objects(self, output_dict, img_path, category_index, threshold=.5) -> list:
        
        def image_size(image_path):
            im = Image.open(img_path)
            width, height = im.size
            return width, height

        max_detection_classes = max(output_dict['detection_classes'])
        predict_bboxes = []

        for num in range(max_detection_classes):
            class_num = num + 1

            for i in range(len(np.where(output_dict['detection_classes'] == class_num)[0])):
                index_for_class = np.where(output_dict['detection_classes'] == class_num)[0][i]
                detection_score = output_dict['detection_scores'][index_for_class]

                 # if detection_score < threshold:
                 #    continue

                bbox = output_dict['detection_boxes'][index_for_class], image_size(img_path)
                
                classname = category_index[class_num]["name"]                        
                predict_bboxes.append((classname, detection_score, bbox[0], bbox[1], bbox[2], bbox[3]))

        return predict_bboxes
```
