### ISSUE TITLE
Create our detection files 

### ISSUE THREAD

**Issue by isennkubilay** [rafaelpadilla/Object-Detection-Metrics#68]
How can we create our detection files? I mean I don't have a confidence score with detection files. I have ground-truth files.

**Comment by rafaelpadilla** [comment]
Dear @isennkubilay ,

Use the output of your object detector to create the files. You could modify their outputs to create the correct format. If you use YOLOv2, you can use [this](https://github.com/rafaelpadilla/darknet) project to obtain the detection files.

**Comment by isennkubilay** [comment]
I originally trained my data with [https://github.com/experiencor/keras-yolo2] I need evaluation metrics to compare my results.  How can i get mAP score?

**Comment by rafaelpadilla** [comment]
Dear @isennkubilay ,

I am not familiar with this project. But taking a look at [this](https://github.com/experiencor/keras-yolo2/blob/master/Yolo%20Step-by-Step.ipynb) notebook, if you call the function `decode_netout`, you will get the detections. You need to create the detection files with these bounding boxes.
