### ISSUE TITLE
False Positive (FP): A wrong detection. Detection with IOU < threshold

### ISSUE THREAD

**Issue by kli-nlpr** [rafaelpadilla/Object-Detection-Metrics#7]
why  IOU < threshold ？ 
I think FP is one detection whose IOU > threshold but with the wrong label.
Thanks

**Comment by rafaelpadilla** [comment]
Dear @kli-nlpr,

*IOU < threshold is a FP*. See the explanation below:

We define IOU as:
![iou](https://user-images.githubusercontent.com/31217453/43682605-1b088282-9850-11e8-833e-13fd6e4b0872.png)

So, the max value of IOU is 1 and this is the case where the "area of overlap" = "area of union". In this case the detection and the ground truth have a perfect match. This is a perfect TP.

Cases where the IOU < 1, the detector misses part of the ground truth. The threshold is a  tolerance factor limiting the area that you will consider a TP. Let's say you set your threshold to 80%. In this case you still consider a TP if you detect at least 80% of the area of the ground truth. In this case, detections with IOU < 80% are FP. So, if you are being very strict and conservative, set your threshold to higher values. If you are more tolerant, prefer lower IOU values.

Literally we can only compare oranges to oranges. Thus, we only compare detections with the same labels.  Detections of different labels are incomparable, doesn't matter their IOU values. In cases where you detect perfectly an apple (IOU = 1), but you should have detected a banana instead, this is considered a FP.

I hope it helped.

**Comment by kli-nlpr** [comment]
So, "A wrong detection" and  "Detection with IOU < threshold" are two kinds of FP, this make sense, thank you very much for your explanation!

**Comment by rafaelpadilla** [comment]
You're welcome! :)
