### ISSUE TITLE
Properly handle "difficult" objects?

### ISSUE THREAD

**Issue by bwang-delft** [rafaelpadilla/Object-Detection-Metrics#71]
I think the current implementation may not handle "difficult" objects in the correct way. By definition, "difficult" objects do not count as false negative if they are not detected. However, if a detection overlaps with a "difficult" object (iou > 0.5) then this detection is not counted as false positive either. The current implementation does not handle "difficult" objects explicitly. If users include them as ground truth then we may get more false negatives due to not being able to detect them. If on the other hand users do not include them as ground truth then we may get more false positives due to penalizing detections that overlap with "difficult" objects.

**Comment by rafaelpadilla** [comment]
Dear @bwang-delft,

You are right. In this implementation we do not differentiate the called "difficult" objects in the VOC challenge. 

In the official implementation, the objects tagged as "difficult" are ignored and here we don't.

Thanks for your comment on that. That feature can be implemented in future versions.
