### ISSUE TITLE
Another measurement

### ISSUE THREAD

**Issue by bhaswara** [rafaelpadilla/Object-Detection-Metrics#72]
Hi @rafaelpadilla , Do you know how to get true positive, true negative, false positive, and false negative from your code? Thanks

**Comment by bhaswara** [comment]
Hi @rafaelpadilla , thanks for your reply. I'm sorry if i ask again. 
In the link that you shared, I only found how to get the true positive and false positive, but none for the true negative and false negative. Can you give example for this? Thank you

**Comment by rafaelpadilla** [comment]
@bhaswara ,

True Negative does not apply in this case. Note that TN would represent a corrected misdetection. In the object detection task there are many possible bounding boxes that should not be detected within an image.

Use the following relation to calculate the FN:
FN = all ground truths - TP

Regards

**Comment by bhaswara** [comment]
Thanks for the reply. 
Ok, then for this case, the false positive rate cannot be calculated because as i know in the equation for calculation of false positive rate, it needs true negative. Am I right for this? Or is there any way to calculate the false positive rate? Thank you

**Comment by rafaelpadilla** [comment]
Hi @bhaswara ,

You still can get the right amount of FP detections. There also another relation that associates the FP with your detections. They are explained [here](https://github.com/rafaelpadilla/Object-Detection-Metrics#true-positive-false-positive-false-negative-and-true-negative).

In summary, this is how you get them:

i)   **TP** and **FP**: Get from the `GetPascalVOCMetrics` function
ii)  **FN*: Get from the relation **FN = all ground truths - TP**
iii) **FP*: Get from the relation **FP = all detections - TP**

Best regards
