### ISSUE TITLE
Can it run on GPU?

### ISSUE THREAD

**Issue by invisprints** [rafaelpadilla/Object-Detection-Metrics#73]
I run eval methods in every epo during training, but i found it runs very slow. So how could I move metrics methods in GPU? thx

**Comment by rafaelpadilla** [comment]
Dear @invisprints ,

You could try using pytorch to try to speed up the process, but I am not very convinced the calculation is the bottleneck and have doubts if gpu will really accelerate the process. 

There are some contributions done in [this](https://github.com/rafaelpadilla/Object-Detection-Metrics/pull/43) PR. They are supposed to accelerate the detections. I havent tested it yet. I suggest you to try it.

Best regards

**Comment by invisprints** [comment]
Thank you very much! I'll try it later.

**Comment by invisprints** [comment]
Wow, it works well both on CPU and GPU! In my case, time reduced from about 150s to 15s, and GPU runed a bit slower than CPU.

**Comment by rafaelpadilla** [comment]
@invisprints,

Nice to hear that! :) Did you try the PR code? Are the results the same as the slower original code?

**Comment by invisprints** [comment]
Yes, the PR code improved performance much. I just test it during training, so haven't check the results. But they looked similar.
