### ISSUE TITLE
Pascal VOC - extract threshold values per each curve point

### ISSUE THREAD

**Issue by SnowRipple** [rafaelpadilla/Object-Detection-Metrics#75]
Hi,
       I would like to calculate threshold values for given precision/recall point using GetPascalVOCMetrics() method. However I'm confused how every box confidence scores are used in conjuction with IOU threhold.

From the code  I can see that only IOU threshold is used to determine if a detection is a FP or TP. The confidence scores seems to be ignored. I assumed that detections' confidence scores are also used to calculate TP/FP however it is seems that they are not. As such I don't know how to extract threshold values per each precision/recall point.

What am I missing?

**Comment by austingg** [comment]
you can filter bounding boxes by scores in advance.

**Comment by stratomaster31** [comment]
[Here](http://host.robots.ox.ac.uk/pascal/VOC/voc2012/htmldoc/devkit_doc.html#SECTION00050000000000000000), in section 4.4, says that only the IoU is taken into account to consider a detection as a TP or FP.

For the thresholds, you have to interpolate the curve as demonstrated in this repo.
