### ISSUE TITLE
How to order on the same confidence

### ISSUE THREAD

**Issue by johanek2** [rafaelpadilla/Object-Detection-Metrics#77]
Hi, in the readme example there are two detections (R, Y) with the same confidence but one of them is labeled TP and the other is labeled FP. When creating the Precision x Recall curve the order of these makes a difference for the final mAP score. Is there a rule on how to order these?

**Comment by rafaelpadilla** [comment]
@johanek2 ,

Thank you for your comment.

It was very well noted! According to my investigations, there is no rule to apply on this case.

Indeed, it will make difference on the calculation of Precision and Recall, but for a real dataset (not the toy example I used here), the way you sort bounding boxes with tied confidences may not make a big difference. I believe that, depending on your detector, the confidence is reported as a float / double with many decimal places of precision. So having the same confidence in some cases may not be very common.

Best regards

**Comment by johanek2** [comment]
Thanks, that makes sense. I decided to sort them anyway to make it deterministic by ordering TPs before FPs for detections with the same confidence. This would cause a slightly higher mAP score on average but the affect is negligible.
