### ISSUE TITLE
What if part of my predicted bounding box is out of the image? Should I trim it?

### ISSUE THREAD

**Issue by KLH1472** [rafaelpadilla/Object-Detection-Metrics#8]
Great work! Thanks!
If part of my predicted bounding box is out of the image, should I trim it before I run the pascalvoc.py?
For example, one of my predicted box is described by x, y, w, h. If x<0, should I set x=0 before I run the script? Or I should do nothing, just run the script?
Thanks!

**Comment by rafaelpadilla** [comment]
Dear @KLH1472,

Thanks for your feedback!

You should limit your bounding boxes within the limits of the image. Therefore, if x<0, you must set it to x=0 before running the script.

**Comment by KLH1472** [comment]
Great! Thank you!
