### ISSUE TITLE
All contents of the -sp/--savepath folder are deleted without warning! 

### ISSUE THREAD

**Issue by atpjpta** [rafaelpadilla/Object-Detection-Metrics#83]
I was absolutely shocked to find that line 296 of pascalvoc.py is this:

`shutil.rmtree(savePath, ignore_errors=True)  # Clear folder`

Because of this, I accidentally deleted a very important folder that contained all of my data, documents, and programs from the past month... I am lucky that I have a backup of most of it. Others will not be so lucky, and I'm sure I will not be the last person to assume that specifying the save path as the project's top level directory will be a harmless decision. This line **definitely** should be changed to something like:

`if not os.path.isdir(savePath):
     os.makedirs(savePath)`

or _anything_ besides what it currently is. After this frightening experience, I will be writing a script to check all code downloaded from github for `rmtree` so I never make a mistake like this again... 

With that said, thank you for writing this program. Overall, it is excellent.

**Comment by Legor** [comment]
Couldn't agree more. You should never silently delete any folder or file without a concrete allowance by the user, e.g. using a command switch or a confirmation warning. This should have been fixed right away but sadly it is still persistent in the current version. There isn't any kind of warning either in the doc or code about this issue, what I consider to be a Very high risk of loosing any data you have on your system.

**Comment by chrisrapson** [comment]
Absolutely agree with the two previous commenters. It is not ok to recursively delete folders without user confirmation or even a notification! The readme only says this:


-sp,--savepath | folder where the plots are saved | python pascalvoc.py -sp /home/whatever/my_results/ | Object-Detection-Metrics/results/
-- | -- | -- | --


My personal situation was that I wanted my savepath to be the parent folder above my detections and GT - but I ended up accidentally deleting both!

My untested suggestion would be:
```
os.makedirs(savePath, exist_ok=True)
for root, dirs, files in os.walk(savePath):
    if (files) and (root == savePath):
        print('pascalvoc expects savepath to be an empty directory. Please delete the contents or select a different savepath')
```
Note that this allows savePath to have existing subfolders, but not files

**Comment by rafaelpadilla** [comment]
Hi,

Thanks for your great feed back on this. 

This is an extremely important issue. It will be solved in the next version.

**Comment by rafaelpadilla** [comment]
This issue was solved. See it [here](https://github.com/rafaelpadilla/Object-Detection-Metrics/blob/master/pascalvoc.py#L296)

Now the user needs to confirm the removal of the folder and its contents.

I think this issue can be closed now.

Thank you for your feedback.
