### ISSUE TITLE
How can I calculate confusion matrix for object detection ? 

### ISSUE THREAD

**Issue by dangmanhtruong1995** [rafaelpadilla/Object-Detection-Metrics#86]
Hi, I need to calculate confusion matrix, but I do not understand how to do so in an object detection context, because usually you calculate AP for each class, then take average to get mAP, but it does not seem very straightforward to find confusion matrix. Please help me, thank you very much.

**Comment by rafaelpadilla** [comment]
Hi @dangmanhtruong1995 ,

In a quick google search, I found:

https://medium.com/moonvision/smart-object-detection-evaluation-with-confusion-matrices-6f2a7c09d4d7

https://towardsdatascience.com/confusion-matrix-in-object-detection-with-tensorflow-b9640a927285

They might be useful.
