### ISSUE TITLE
mAP values for IoU threshold > 0.5

### ISSUE THREAD

**Issue by ammaradel** [rafaelpadilla/Object-Detection-Metrics#88]
I tested you code on a custom dataset, and compared the results to [the Tensorflow object detection API evaluation code](https://github.com/tensorflow/models/blob/master/research/object_detection/metrics/offline_eval_map_corloc.py). The mAP@IoU=0.5 value was almost identical, but the result was very different at higher IoU thresholds (0.75, 0.9, ...).

I may have made some mistake when applying either code, but could you please check whether the original Pascal VOC matlab code gives you the same results as your code, for IoU thresholds higher than 0.5?

Thanks.

**Comment by rafaelpadilla** [comment]
Dear @ammaradel ,

Thank you for your message.

Our implementation is exactly the same as PASCAL VOC version in Matlab. Regardless the IOU threshold, the results obtained with our code are identical to the Matlab version.

The tensorflow evaluation code is the version used by COCO and some other challenges. It is not guaranteed that the results are the same as PASCAL VOC.

In the future we expect to have Tensorflow's evaluation metrics in our repository.

Regards,
Rafael
