### ISSUE TITLE
Unable to execute pascalvoc.py

### ISSUE THREAD

**Issue by memon-aliraza** [rafaelpadilla/Object-Detection-Metrics#9]
I am getting the following error while executing the file. 

~/Documents/Object-Detection-Metrics $ **python pascalvoc.py -h**
  File "pascalvoc.py", line 197
    [print(e) for e in errors]
         ^
SyntaxError: invalid syntax
arm@arm-nb-t470p ~/Documents/Object-Detection-Metrics $ **python pascalvoc.py -v**
  File "pascalvoc.py", line 197
    [print(e) for e in errors]
         ^
SyntaxError: invalid syntax

Therefore, I am unable to execute the script on my generated GT and Detections.

**Comment by manyaafonso** [comment]
I have exactly the same problem. It would be nice if the readme file were to have an example on how to run over samples 1 and 2.

**Comment by NPetsky** [comment]
You have to change the line [print(e) for e in errors] to 
for e in errors:
    print(e)
then it works (I guess his line works in python 3 but not in python 2)

**Comment by memon-aliraza** [comment]
No luck yet!

**Comment by NPetsky** [comment]
Do you get the same error or another?

**Comment by memon-aliraza** [comment]
I got the following message:

Traceback (most recent call last):
  File "pascalvoc.py", line 15, in <module>
    from BoundingBoxes import BoundingBoxes
  File "/home/user/Object-Detection-Metrics/lib/BoundingBoxes.py", line 121
SyntaxError: Non-ASCII character '\xe2' in file /home/user/Object-Detection-Metrics/lib/BoundingBoxes.py on line 121, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by NPetsky** [comment]
I got this error too, you have to delete one sign from the comment -> in "participant’s system" in line 121 you have to delete the ' sign (I think he accidentally used a wrong sign)

**Comment by memon-aliraza** [comment]
Thanks for your support. I deleted the ' sign but got the same issue. Afterwards, I deleted the whole comment and it worked! Thanks!
