### ISSUE TITLE
When one bounding box has multiple detected result

### ISSUE THREAD

**Issue by kaka1346** [rafaelpadilla/Object-Detection-Metrics#90]
Hi Developer, 

I have a model that can return more result in one predicted box with confidence score, like bellow
Been 0.4901 68 280 196 611
Coffee 0.4475 68 280 196 611
Apple 0.4455 68 280 196 611

Should i update all result in all above result in the detected .txt file or just update one result which have highest score ?

Thank in advance

**Comment by rafaelpadilla** [comment]
@kaka1346 ,

What do you mean by "update all result in all above result in the detected .txt" ?

If your model detects the same bounding box coordinates for different objects in the same image, you should keep your detected file as it is: 

Been 0.4901 68 280 196 611
Coffee 0.4475 68 280 196 611
Apple 0.4455 68 280 196 611

**Comment by kaka1346** [comment]
@rafaelpadilla,

yes, i'm doing like you commented, but maybe not the different objects, because ground truth of the object just is one of them like:
 Coffee  68 280 196 611.
it's ok ?

**Comment by rafaelpadilla** [comment]
Hi @kaka1346,

If in your image (ground truth) there is only 1 object to be detected (the "Coffee"), then, yes, make your ground-truth file like:
Coffee 68 280 196 611.

In your example, as your detector is detecting incorrectly 2 other objects ("Been" and "Apple"), for this particular image you will have 1 TP ("Coffee") and 2 FP ("Been" and "Apple").

**Comment by kaka1346** [comment]
@rafaelpadilla 
Yeap, I understand. Thank for making great tool
