### ISSUE TITLE
Ground truth samples reuse

### ISSUE THREAD

**Issue by loicdtx** [rafaelpadilla/Object-Detection-Metrics#95]
If I understand correctly your evaluation [code](https://github.com/rafaelpadilla/Object-Detection-Metrics/blob/6402fe24433c81156cb597c5d6883e707b888a3c/lib/Evaluator.py#L99-L121), a same ground truth bounding box can be used several times; that is if two detection bounding boxes intersect with that ground truth bounding, both with IOU > IOUthreshold, they'll both be considered true positives. 
Is that correct, and is that the expected behavior?

Note, if you're interested I made your code more pip friendly + a few changes [here](https://github.com/loicdtx/odeval). Just for my own needs, not for pypi or anything; however, if you're interested I'm happy to assist in making your code pypi ready.

**Comment by rafaelpadilla** [comment]
@loicdtx,

For each detection, all groundtruths are evaluated. BUT:

i)  only 1 groundtruth can be associated (matched) with a detection
ii) each detection can be associated (matched) with 1 or 0 groundtruth

So, if two detection bounding boxes intersect the same ground truth bounding, both with IOU > IOUthreshold, only the detection 
with the highest confidence will be TP. The other will be FP.

Yes, your help is very welcome. What did you actually changed in your repo? Please, list here all changes you made. Then if they are relevant, we can consider it being part of the master. :) I know it took me months to answer your issue, but now I will dedicate more time to answer them all as quick as possible.

Best regards

**Comment by loicdtx** [comment]
@rafaelpadilla, thanks for your response.
Which part of the code ensures that your statement (i) is true? By just looking at the code it looks to me that the gts are fully recycled for every detection. Maybe I missed a part. 

I'm afraid I won't be able to help much with restructuring the project into a package. I changed job and I do not work on object detection at the moment. The repo I created still exists though and it could be a starting point.

**Comment by rafaelpadilla** [comment]
@loicdtx 

The statement (i) is guaranteed by [this](https://github.com/rafaelpadilla/Object-Detection-Metrics/blob/6402fe24433c81156cb597c5d6883e707b888a3c/lib/Evaluator.py#L112) if clause.

When GT is matched with a detection, it is set as "seen". For more reference check [this](https://github.com/rafaelpadilla/Object-Detection-Metrics/pull/112) discussion.

Ok. I will take a look at your repo carefully. Best wishes on your new job! :)
