### ISSUE TITLE
paper

### ISSUE THREAD

**Issue by kaijieshi7** [rafaelpadilla/Object-Detection-Metrics#96]
I cant find the paper on Internet, can you send the PDF to my email account:1638961687@qq.com?
Thank you

**Comment by rafaelpadilla** [comment]
Dear @kaijieshi7,

The paper was sent to your email.

**Comment by pHidayatullah** [comment]
> Dear @kaijieshi7,
> 
> The paper was sent to your email.

Dear @rafaelpadilla @kaijieshi7, could you please sent it to me also.
My email is petonx@gmail.com.

Thank you in advance.

**Comment by rafaelpadilla** [comment]
@pHidayatullah ,

I have just sent you the paper.

**Comment by pHidayatullah** [comment]
> @pHidayatullah ,
> 
> I have just sent you the paper.

Thank you very much..
