### ISSUE TITLE
How to make a detection file correctly?

### ISSUE THREAD

**Issue by Ujang24** [rafaelpadilla/Object-Detection-Metrics#97]
I used YOLOv3 for making detections.
For example we have 1 class with 500 GT objects.
I used confidence th= 5% in detection. There are more or less 420 detection.
The detection result has been converted into this repo's format and mAP can be calculated.

Someone said, mAP is calculated as average AP that is average Precision for all (or 11) points on Precisions-Recall curve that is built for each value of threshold from 0.0 to 1.0. Is this also valid for this repo?
I want to confirm, should I perform detection with confidence th = 0%?
However, it will give thousands of detections (which gives alot of FP).

Thx

**Comment by rafaelpadilla** [comment]
Dear @Ujang24 ,

Just a small correction. mAP is the average AP among all classes. So, for each class you have a certain AP. If you sum the APs and divide by the number of classes, you have the mAP.

Yes, this repo supports two different calculations of the AP: [11-point interpolation](https://github.com/rafaelpadilla/Object-Detection-Metrics#11-point-interpolation) and [interpolating all points](https://github.com/rafaelpadilla/Object-Detection-Metrics#interpolating-all-points). The one you mentioned is the 11-point interpolation.

By default, this implementation uses the method "interpolating all points".  If you want to use the 11-point interpolation, change the functions that use the argument `method=MethodAveragePrecision.EveryPointInterpolation` to `method=MethodAveragePrecision.ElevenPointInterpolation`.

I strongly recommend you to read the README file and check the samples.

Best regards,
Rafael
