### ISSUE TITLE
Formatting for YOLO ground truths

### ISSUE THREAD

**Issue by astoncrawley** [rafaelpadilla/Object-Detection-Metrics#98]
I am using your code to compare bounding boxes that I have generated using my own code to ground truths labelled in YOLO format (relative and <class> <left> <top> <width> <height>). My detected bounded boxes are in the completely opposite format (absolute and <class> <confidence> <left> <top> <right> <bottom>).

I am using the appropriate code in the command line: python pascalvoc.py -gtcoords rel -imgsize 2560,1920 -detformat xyrb

However, I seem to get an Assertion error at Evaluator.py line 395, it looks as though your code takes my ground truths and outputs them in the form <class> <left> <bottom> <right> <top>, making my IOU value negative. 

I have made a change in the utils.py script line 81, taking away from yIn instead of adding. 
Is this the correct way to make the change and if not are YOLO outputs generally formatted in this way?

Many thanks for your help

**Comment by rafaelpadilla** [comment]
Dear @astoncrawley,

The format of the ground-truth bounding boxes can be either **x1 y1 x2 y2** or **x y width height**:
`-gtformat xyrb` or `-gtformat xywh `

The format of the detection bounding boxes can be either **x1 y1 x2 y2** or **x y width height**:
`-detformat xyrb` or `-detformat xywh`

The groundtruth coordinates can be either **absolute** or **relative**:
`-gtcoords ab`s or `-gtcoords rel`

The detection coordinates can be either **absolute** or **relative**:
`-detcoords abs` or `-detcoords rel`

In your case, make sure to specify all 4 tags.

Also take a look at the [sample 1](https://github.com/rafaelpadilla/Object-Detection-Metrics/tree/master/samples/sample_1) example. Adapt it to plot the bounding boxes on your images to compare the results.

Good luck!

**Comment by astoncrawley** [comment]
Dear @rafaelpadilla,

Thanks so much for your help, it turns out that I was creating my bounding boxes incorrectly and plotting the bounding boxes on the image was very helpful
