### ISSUE TITLE
Need precision and recall per image api

### ISSUE THREAD

**Issue by tengerye** [rafaelpadilla/Object-Detection-Metrics#99]
Is there any plan to implement calculating precision and recall per image?  For example, given a threshold, calculate the precision and recall of an image.

Thanks a lot.

**Comment by rafaelpadilla** [comment]
Hi @tengerye,

It is partially implemented. I mean, you need create the object BoundingBoxes individually for each image. You could adapt the code for that.

There is no plan to implement it this way, but you can take a look at [this](https://github.com/rafaelpadilla/Object-Detection-Metrics/tree/master/samples/sample_2) sample and adapt it for your needs.

Best regards
